### ISSUE TITLE
JEveAssets Won't Open

### ISSUE THREAD

**Issue by Calladen** [GoldenGnu/jeveassets#103]
Running on Windows 10 64-bit with the latest Java installed.  JEveAssets is double clicked but nothing happens.  It's associated with javaw file type.  I was able to get it running on my old Windows 7 computer but it hangs on "verifying API" there.  I get the sign on window for Eve and select a character but the Authorize button never highlights when I click it.  Not sure what the issue is.  I've uninstalled and reinstalled both Java and JEveAssets multiple times but the results are the same.  Any advice would be welcome.  Thank you.

**Comment by GoldenGnu** [comment]
Please see: https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#bugs 
It's not certain the log exist, as you exit so soon after starting, but, if does, please, email it to me

**Comment by GoldenGnu** [comment]
I assume this was fixed? Closing it now, please, comment here if you still have this issue and I will re-open it.
