### ISSUE TITLE
Add option to use logarithmic scaling in Worth Tracker

### ISSUE THREAD

**Issue by dao** [GoldenGnu/jeveassets#111]
Logarithmic scales are perfect for illustrating % changes. As my space wealth grows, a log scale would naturally reflect the fact that making 100 million is now as significant to me as making 10 million used to be, and 1 million before that.

**Comment by GoldenGnu** [comment]
A quick google show that the chart library jEveAssets uses does support that feature.
I have to do proper research of the chart support, before I will know for sure.
But, it looks promising.

Ref:
http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/axis/LogAxis.html
http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/axis/LogarithmicAxis.html

**Comment by GoldenGnu** [comment]
Released in 6.4.0
