### ISSUE TITLE
Tracker: Skill points value

### ISSUE THREAD

**Issue by GoldenGnu** [GoldenGnu/jeveassets#116]
Keep track of the value of skill points in the tracker/isk/values tools
https://esi.evetech.net/ui/#/Skills/get_characters_character_id_skills have total skills points (`total_sp` and `unallocated_sp` _optional_)
valued via the injector prices:
(full injector - empty injector) / skill points per injector = 1 skill point value

> A character will have to have 5.500.000 Skill points minimum in skills to be able to extract skill points as it is not possible to extract skill points below 5.000.000 Skill points.Unallocated skill points DO NOT count towards those 5.500.000 SP and can not be extracted until they have been applied.

**Comment by GoldenGnu** [comment]
Math from Staxed on discord:
(((totalSP-5mil)/500000)*(Injector price - Extractor price))

**Comment by ChemicalRascal** [comment]
I like the idea of tracking SP value, as someone with an SP farm. But I wonder if it'd be feasible to have some metrics relating to that configurable on a per-character basis. A different "base level SP", for example, given some SP might be intentionally never extracted (ergo, if I'm running PI on those characters as well, well there's a bunch of SP that is effectively without value). And I'm never going to extract from my combat main(s), or ratters, beyond a certain point.

But adding that to the account management window, which is the only place I could see doing that in the existing UI, would be... bleh.

**Comment by GoldenGnu** [comment]
I'm going to start working on this issue, as I already added skill for another feature.

**Comment by GoldenGnu** [comment]
Released in 6.6.0
