### ISSUE TITLE
Plex Vault

### ISSUE THREAD

**Issue by FireCulex** [GoldenGnu/jeveassets#12]
Plex vault doesn't get counted as assets.

**Comment by GoldenGnu** [comment]
There is already an issue for that on UserVoice: https://jeveassets.uservoice.com/forums/217172-general/suggestions/20563933-since-the-plex-changes-i-cannot-see-my-plex-anymor
...In short: It's not possible due to there being no API for the plex vault

**Comment by GoldenGnu** [comment]
I want to add, that it's very unlikely that will ever be an API for the plex vault.
The new API (ESI) does not have any account related information and it will most likely stay like that.
