### ISSUE TITLE
Include fees in Transactions

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#120]
The Suggestion is, in transactions tab, under "value" column, include tax and broker fee in the value.

I don't know if this is possible programing vise but if the time for a transaction is same exact time as when the Tax/fee is paid for that transaction, then one could add up a "transaction" with  "tax/fee sum" and display it under value column. 

One could also calculate the fees and taxes based on standings and skill specified in setting.
For example in settings you can set "Broker relations" skill 1 to 5.
Corporate and faction standing value. 
The "values" column (or a new column) then adds and show a value that has added  the tax and fee figures. 

The Problem is that the app don't know if one bought (green colored values)the item directly from the market or if it was a buy order. For traders this is not an issue because seldom we buy direly. For those one can ignore the values in the app. Same for sell orders (red colored values).

If possible, The first option is preferred though.

Thanks you again for a great program.

Edit: 
The function i want is to be able to see the real average cost of an item or when select several items and right click. 
![bild](https://user-images.githubusercontent.com/34539717/68187174-3c219a80-ffa6-11e9-9d6d-0ac7cbacf4d4.png)

Right now i have to switch to my excel and add the figures to calculate fees for buy orders and tax+fee for sell orders. Being able to see this number in the app almost certainly will remove the need to switch to excel.

**Comment by GoldenGnu** [comment]
This extend #125 and should be done at the same time, if possible

**Comment by GoldenGnu** [comment]
This apply to both the Market Orders tool and the Transactions tool - however, tax is not directly linkable with orders and may have to be skipped for the Market Orders tool

**Comment by GoldenGnu** [comment]
Transaction Tax is easily linked with transaction by date
Broker's Fee is easily linked with market orders by date

However;
Linking Transaction Tax with market orders would require a lot of guessing....
Linking Broker's Fee with Transaction would require a lot of guessing...

**Comment by GoldenGnu** [comment]
Released in 6.2.0
