### ISSUE TITLE
Wrong calculation of asset value in station

### ISSUE THREAD

**Issue by Kreastr** [GoldenGnu/jeveassets#121]
![kuva](https://user-images.githubusercontent.com/2335508/70791917-c7a9fa80-1da0-11ea-931e-452d3f50245c.png)

On screenshot total values in stations Podion VIII and Litom XI do not match the sum of categories. It seems that Office value is calculated twice and within Asset Safety individual wrap is calculated twice as well.

**Comment by Kreastr** [comment]
The calculation error is apparently some runtime one. Because calculation fixed itself after restart.

**Comment by GoldenGnu** [comment]
Thank you for your bug report.
I will try to get time to look into before next release

**Comment by GoldenGnu** [comment]
I was never able to reproduce the error state, but, I have committed a possible fix for it.
It will be included in the next release.

If, after updating to the future release, you are still able to reproduce it again, please make comment on this issue and I will reopen it and investigate again.

**Comment by GoldenGnu** [comment]
Released in 6.2.0
