### ISSUE TITLE
Transactions: Add columns transactions profit/percent/price and tax

### ISSUE THREAD

**Issue by Sabistik** [GoldenGnu/jeveassets#125]
I want to do daily sell report. In 'Market Orders' tab i don't have exact sell date so it is difficult.
I can use 'Transactions' tab but there is no 'profit' column - which is the most important for me.

**Comment by GoldenGnu** [comment]
This is going to resolve by adding all the transactions profit/percent/price columns to the transactions tool.

Should also look into adding a fee/tax column.

**Comment by GoldenGnu** [comment]
Released in 6.2.0
