### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by callpower1712** [GoldenGnu/jeveassets#126]
keep getting 401 and 403 download failures

**Comment by GoldenGnu** [comment]
I will need the log to debug it: https://jeveassets.nikr.net/faq#bugs
EVE was under DDoS attack yesterday, so, that may be why ESI is unstable.
I will look into as soon as I have the logs

**Comment by r2n2** [comment]
At least for me 401/403 errors were entirely due to an expired SSI token.  Re-authorized and the next day after the cache had time to expire everything is green on updating.   May fix your problem as well.  SSO tokens apparently only last 30 days and need to be re-authorized after that time period.

**Comment by GoldenGnu** [comment]
I’m going to assume this have resolved itself (since I never revived the logs). Please, leave a comment to get this issue re-opened
