### ISSUE TITLE
BPO in active industry job being reported as BPC

### ISSUE THREAD

**Issue by rayanth** [GoldenGnu/jeveassets#127]
I have an Orca BPO that is currently in an Industry job, performing 1 level of ME Research from  ME 8 to ME 9, with 12d remaining on the job

jEveAssets is reporting it as a BPC, though it correctly identifies that it is in an Industry Job, and the correct owner.

jEveAssets version 6.1.3, with latest SDE update.

From some probing, it appears that the only ESI endpoint that reveals a blueprint that is in industry is the Industry/Jobs endpoint, so it makes sense that not all info is available and assumptions must be made. However, I would suggest checking the `activity_id` on the industry/jobs endpoint and casting the assumption from that:

1 = Producing (could be BPC or BPO)
3 = TE Research (must be BPO)
4 = ME Research (must be BPO)
5 = Copying (must be BPO)
8 = Invention (must be BPC)

**Comment by rayanth** [comment]
following up on this, strangely it's only reporting this for two particular jobs - an Orca BPO and a Porpoise BPO, The Porpoise is in TE research. Verifying against ESI, it does identify activity id as 3, (and the Orca as 4) but All other industry jobs on 5 characters are correctly reported as BPO's in jEveAssets...

**Comment by GoldenGnu** [comment]
Thank you for your bug report 👍 

Could you check the following for me:
in `GET /characters/{character_id}/industry/jobs/` value of `licensed_runs`
in `GET /characters/{character_id}/blueprints/` value of `runs` (matching `jobs.blueprint_id` with `blueprints.item_id`)

**Comment by GoldenGnu** [comment]
Released in 6.2.0
