### ISSUE TITLE
Move to ESI

### ISSUE THREAD

**Issue by GoldenGnu** [GoldenGnu/jeveassets#13]
## Release Plan
- [x]  All characters endpoints are completed
   - Released
- [x]  All corporations endpoints are completed
   - Released
- [x]  All endpoints are completed
   - New version will be released with XML support removed
      - This will be postponed until the XML API is removed by CCP

### Characters
- [x]  Assets
- [x]  Balance
- [x]  Blueprints
- [x]  Contracts
- [x]  Industry Jobs 
- [x]  Market Orders
- [x]  Journal
- [x]  Transactions
- [x]  Ship and container names

### Corporations
- [x]  Assets
- [x]  Balance
- [x]  Blueprints
- [x]  Contracts
- [x]  Industry Jobs
- [x]  Market Orders
- [x]  Journal
- [x]  Transactions
- [x]  Ship and container names

### Public
- [x]  Resolve characterIDs and corporationIDs to names
- [x]  Conquerable Stations

**Comment by douglas24** [comment]
Will this add the price API from the game? Right now with eve-central broken my prices are all 0.

**Comment by GoldenGnu** [comment]
It will not. The latest version (4.1.5) have eve-central disabled and will use eve-marketdata instead.
I'm still hoping that eve-central will return, once/if it does I have some optimizations I can do, to make the import faster than it was before (threads and faster parsing of the prices).

Adding prices from ESI is hard, because, I would have to do all the math myself. It's also a lot slower as you need to download a lot more data. Eve-central and eve-marketdata serve calculated prices and is a lot easier to use than the ESI orders endpoint. With ESI you literately download all the orders. 

The plan is that once parity is completed, I will work on adding new stuff from ESI.
Some of the things I'm considering is:
- Assets in Planetary Colonies
- Assets in Customs Offices
- ESI UI endpoints (Can open windows in game)
- Loyalty Points
- Corporation wallet division/hangar names

Note: they are not all currently possible with ESI, but, may be in the future

**Comment by douglas24** [comment]
I'll say +1 to adding Loyalty Points. I hope this gets added very soon, unlike how long it took for CCP to add an endpoint for it.

**Comment by GoldenGnu** [comment]
The migration is now complete.
Please, create new issues for any ESI feature you would like added to jEveAssets
