### ISSUE TITLE
Transactions: Match market orders export to file

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#133]
If this one can be done then traders would have the ultimate tool.

Background first.

There are apps for traders that help update or create orders faster. The function for these apps work like this, in the EvE "trade window" when pushing the "export to file" button , either the lowest sell price or highest buy price,  plus 0,1 ISK (or an amount one chooses), is copied to clipboard. That number is then copied (CTRL+V) in the price field when one creates and order or change price.

The function i am suggesting is to use the same mechanism ("export to file" ) to search and show that item in transactions tab. This would remove the need to copy the item name in the client, which is a hassle in itself,  and then switch to the app and search that item in Transactions tab.  

As a bonus for those with one monitor the app had the function "always on top".

One could have the "rule" in the app that this would only be done when the transaction tab is on
This could also be an option one can chose in the transaction tab or in settings.

I am not a programmer and don't know if this is possible with Java or not and because of this if this is not possible a simple rejection answer would be sufficient. I don't want GoldenGnu to spend his precious, valuable and highly appreciated  time explaining to me why it is not possible.

Much love from a perpetual user of the app, and if there is a god i ask her he bless GoldenGnu eternal life, or if aliens do exist may GoldenGnu be abducted, genetically modified, and gain immortality that way.

**Comment by GoldenGnu** [comment]
It is possible. The hard part is making it work cross platform, as the save location is dependent on the OS. I can test it myself on windows and Linux, but, I do not have access to a Mac to test it.

**Comment by Amme11** [comment]
Because i am a selfish person and use windows i vote to only do it for windows and skip Linux and MAC.

**Comment by GoldenGnu** [comment]
That is never an option to me. The main reason jEveAssets is written in Java is to make it cross platform.

**Comment by GoldenGnu** [comment]
Closing this in favor of #147
