### ISSUE TITLE
Auto margin tool similar to Elinor

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#134]
Elinor is a tool that uses "export to file"  function within the client in the market window to copy a figure to clipboard for easier updating and creating orders.

In march when the new order fee and the ticker change take to effect Elinor will be useless.

The problem is that Elinor is not supported or updated so it will not be able to take to effect the ticker change and the new fee.

Hopefully the "Elinor feature" would be easy to program and i don't know if such a function, if you chose to implement, would or should be part of this app or it would be a separate app. 

I don't know much about programing, but if you are using "export to file" function to implement the previously suggested feature to include fees and taxes to the Transactions tab, you might find the function that Elinor has would be easy or hard to also implement after you have familiarized yourself with "export to file" mechanize. 

Elinor could be hard to find on the web but if you want to test the app i could email it to you, its a small app that don't need installing.

![bild](https://user-images.githubusercontent.com/34539717/75950424-72661c80-5ea9-11ea-8f48-bfda0a899fd7.png)

![bild](https://user-images.githubusercontent.com/34539717/75519727-2d9f3900-5a04-11ea-973d-8520365a48bf.png)

**Comment by Amme11** [comment]
Also i would add that this function is legal, other apps such as eve mentat already uses it.

**Comment by Sabistik** [comment]
I vote for it! last Elinor version is available here: https://github.com/Slivo-fr/elinor-reloaded 
It is simplest version. i think we need only few things. 
- calculation current profit margin for out skills
- auto copy sell/buy price

**Comment by GoldenGnu** [comment]
Released in 6.3.0
