### ISSUE TITLE
Shortcut for open market details

### ISSUE THREAD

**Issue by Sabistik** [GoldenGnu/jeveassets#137]
Idea for tools -> Market orders:

It would be nice to add some shortcut which will go to next row and trigger 'open market details'. This would speed up order editing.

**Comment by GoldenGnu** [comment]
I'm not sure how to do this, as the table can have multiple rows selected, making it hard to what one to move to and open.

**Comment by GoldenGnu** [comment]
I'm not going to add a shortcut key, however, I'm going to make the market details table button clickable with the space.
So, you will be able to do:
1) Click the top row market details cell  (trigger 'open market details')
2) Press enter or arrow down (to go to next row)
3) Press space (trigger 'open market details')

Repeat step 2 and 3 until you get to the end of the table

**Comment by GoldenGnu** [comment]
Released in 7.0.0
