### ISSUE TITLE
"Cascading" Stockpiles

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#141]
Explaining with an example: in Stockpile A, I would like to be able to add Stockpile B as an item and set its Minimum Count (say 3 for the sake of my example), just as if I was adding any other item. The "Stockpile B" item inside Stockpile A now acts a reference to my Stockpile B: if I generate a Shopping List for A with a 10x multiplier, 10x3x all items of Stockpile B are added to my Shopping List instead of the "Stockpile B" item.

I feel this would be especially useful when using Stockpiles for Manufacturing. If would become possible to make Stockpiles for various components, then reference these stockpiles in other stockpiles used for finished products requiring a certain amount of these components.

I am happy to clarify if my explanation isn't clear.

**Comment by GoldenGnu** [comment]
I really want to do this, as it’s an really interesting feature

**Comment by GoldenGnu** [comment]
Next step is user feedback in a dev build (when we're closer to release of 6.6.0)

**Comment by GoldenGnu** [comment]
Released in 6.6.0
