### ISSUE TITLE
Change Stockpile item colors

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#142]
In Options > Tools > Stockpile, it is possible to set the % ranges that dictate the colors of the items in a Stockpile based on how much is available, but it's not possible to set the colors themselves. As a colorblind person, I'd love it if it was possible to change the colors too.

**Comment by GoldenGnu** [comment]
Accessibility is always a high priority for me and I want to do this ASAP, but, it won't be in the next feature release, as it's currently in feature freeze and this feature would require a fair amount of work.

**Comment by GoldenGnu** [comment]
Red/Green/Yellow color schemes are used in:
- [ ] FilterPanel 
  - Or Groups (use multiple colors)
- [ ] Stockpiles
  - Percent full (JStockpileTable)
- [ ] Assets
  - Reprocessing Colors (JAssetTable)
- [ ] Contracts
  - Included (JContractsTable)
- [ ] Market Orders
  - Outbid (JMarketOrdersTable)
- [ ] Reprocessed
  - Sell or reprocesse (ReprocessedSeparatorTableCell)
- [ ] Transactions 
  - Buy or sell order (JTransactionTable)

**Comment by GoldenGnu** [comment]
Closing in favor of #115
