### ISSUE TITLE
Feature Request:  Filter by Systems based on FW Faction status (to determine Docking access) 

### ISSUE THREAD

**Issue by MaddMaxx2000** [GoldenGnu/jeveassets#155]
Feature request, is there a way to add a field to indicate which faction has control of the system, in FW this dictates which structures you have docking right to or not.  Would be great to have a field to filter out those personal or corp assets which are not accessible.

![image](https://user-images.githubusercontent.com/65825348/82736580-dfdf5780-9cf8-11ea-9ecf-9a7037a5d23a.png)

**Comment by GoldenGnu** [comment]
https://esi.evetech.net/ui/#/Faction%20Warfare/get_fw_systems list the faction owner of  each system. Would that work for your use case?
The alternative is to actually try the structure endpoint for access of each structure - that generates a lot of errors, so, is slow if a lot of structures need to be evaluated.

**Comment by MaddMaxx2000** [comment]
Yea, I think that would work great.

**Comment by GoldenGnu** [comment]
Released in 6.5.0
