### ISSUE TITLE
Feature Request:   Retain Asset Filters upon Exit 

### ISSUE THREAD

**Issue by MaddMaxx2000** [GoldenGnu/jeveassets#156]
Retain the asset filters when exiting/closing jEveAssets, possible making it a selectable option under Options>General or Options>Tools>Assets

I'm using jEveAssets to manage and track over 6 billion assets across multiple characters and normally have a number of asset filters I setup each time I start the program and then just toggle certain one off/of to get the desired listing.

![image](https://user-images.githubusercontent.com/65825348/82855064-3fe02480-9ed8-11ea-83ce-5a9a5c06e6c3.png)

Thanks
Maxx

**Comment by GoldenGnu** [comment]
Any reason you're not just saving/loading the filters?

**Comment by MaddMaxx2000** [comment]
![image](https://user-images.githubusercontent.com/65825348/82892642-d1be5080-9f1d-11ea-87c2-f8f388a4f47e.png)
You mean that Save/Load button staring me in the face.  Sorry, not sure how I missed that since I've used export many times.   I really thought they save/loaded a previous asset list not the filters.

**Comment by GoldenGnu** [comment]
Fair enough. I'm going to close this issue. If you still want the filters to persist between restarts, leave a comment asking to reopen the issue.
