### ISSUE TITLE
Market Orders: Reprocessed column

### ISSUE THREAD

**Issue by sekuzelunder** [GoldenGnu/jeveassets#160]
you can manually change the price of the single ores in the "reprocessed" window... so the amount of ISK for reprocessing a item is very flexible, whats a great function!

it would be very helpful, if you were able to see this price in the "buy-order" window as well.... so if you check your buy orders, you can see if you are below the reprocessing costs of that item....

i would realy love to see this function.

**Comment by GoldenGnu** [comment]
Shouldn't be very hard to add, so, I hope to include it in the next feature release

**Comment by GoldenGnu** [comment]
Released in 6.5.0
