### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sekuzelunder** [GoldenGnu/jeveassets#161]
I use 2 monitors and i use jEveAssets on the second monitor. 

The white colours are difficult for the eyes, if you look to the main monitor. a dark mode, just a black background for jEveAssets, would solve this problem and look good :)

**Comment by GoldenGnu** [comment]
Thank you for your feature request.
There is already an issue for Dark mode: issue #66 (And I already started work on it)
So, I'm close this as duplicate
