### ISSUE TITLE
Usage: Corporation Hangars?

### ISSUE THREAD

**Issue by Sardaukai** [GoldenGnu/jeveassets#162]
Hi,
Maybe I missed something, but is it possible to get corporation hangar assets for stockpile info with new esi?

Cheers

**Comment by GoldenGnu** [comment]
Yes, you need to add a corporation account:
https://jeveassets.nikr.net/faq#add_charactercorporation
Do note that the character needs to be director to get access to assets via ESI.
I’m going to close this issue as resolved.

**Comment by Sardaukai** [comment]
Thx for the super fast answer.
Is the Director role the only way to get it? Or is it maybe possible with some "lower" rights

**Comment by GoldenGnu** [comment]
Assets are not possible with lower rights - some of the other endpoints jEveAssets uses, like the wallet endpoints, only require junior account, but, assets require director.
