### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#163]
I'm starting to receive errors that look like these. Where do I start?

From Update/Structures:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

From Update/Accounts:
Error Code: 401
{"error":"SSO JSON failure","error_description":"unexpected end of JSON input"}

From Update/Data:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

From Update/Dynamic Data/Active Ship:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

From Update/Dynamic Data/Planetary Assets:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

From Update/Dynamic Data/Locations:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

From Update/Dynamic Data/Contract Items:
Error Code: 403
{"error":"unexpected end of JSON input","sso_status":401}

**Comment by GoldenGnu** [comment]
Send me the log via email and I will look into it:
https://jeveassets.nikr.net/faq#bugs

**Comment by GoldenGnu** [comment]
Dev build with a fix for this have been released on [jEveAssets discord](https://discord.gg/8kYZvbM)

**Comment by GoldenGnu** [comment]
Fix released in 6.4.1
