### ISSUE TITLE
Feature Request: Stockpile - Manufacturing filter by Installer

### ISSUE THREAD

**Issue by Sardaukai** [GoldenGnu/jeveassets#164]
Hi,
it would be great if there is another option to filter industry jobs by installer within stockpile.

So it is possible to monitor and manage a larger amount of characters within a corporation. In addition a single player who uses corporation hangars with multiple characters is able to filter other industry jobs at the same station.

**Comment by GoldenGnu** [comment]
Released in 6.5.0
