### ISSUE TITLE
Feature Request - Table menu item for 'Add Transaction Filter'

### ISSUE THREAD

**Issue by tmockler69** [GoldenGnu/jeveassets#165]
Would like to see a menu item to 'Add Transaction Filter' incorporated into the software.  Currently, I copy the item name, change to the Transactions tab, highlight the contents of the filed in an existing filter, and Paste/Overwrite.  Would be much easier with a couple clicks, similar to the 'Add Asset Filter' item already in the software.

**Comment by GoldenGnu** [comment]
I’m adding this to the 6.5.0 because it’s just a minor task, but, it may be moved to a later release, if my current task take too long

**Comment by GoldenGnu** [comment]
Released in 6.6.0
