### ISSUE TITLE
Request for the option to edit the reprocessing yield

### ISSUE THREAD

**Issue by Miss-Dita** [GoldenGnu/jeveassets#166]
It can be done on items that has a reprocessing value but not on those that shows up with a value of zero, even in cases where the item in question does indeed have a yield from the proccess

**Comment by GoldenGnu** [comment]
- [ ] First step is figuring out if the static data can be fixed to include everything that can be reprocessed
- [ ] If that is not possible, then editing the reprocessing yield (saved in a user file), should be made possible

**Comment by GoldenGnu** [comment]
Should be resolved by the latest static data release - May have been due to the SDE being very out of date for some time
