### ISSUE TITLE
Feature Request - Import/Export functionality for routes

### ISSUE THREAD

**Issue by llawwehttam** [GoldenGnu/jeveassets#167]
Hi,

Would it be possible to add import/export functionality for routes so that routes can be shared with corpmates/friends?
At present I'm doing this by copying raw XML from the settings.xml file and talking people through editing it into theirs.

It would also be very useful if systems could be added to a route in bulk rather than individually.

Many thanks

**Comment by GoldenGnu** [comment]
It makes perfect sens to be able to export and import routes.
I want to do this, but, I doubt I will get time for it in this release cycle.
So, It may be a while before I get the time to work on it.

**Comment by GoldenGnu** [comment]
Released in 6.6.0
