### ISSUE TITLE
Tables - Optional "row number" column

### ISSUE THREAD

**Issue by chatelao** [GoldenGnu/jeveassets#169]
Problem:
- I'm an alpha and limited to 17 orders

Suggestion:
- It would be great, if the "Market Orders" view had a row number.
- Then I could ease check the number of orders (total/per location/per sell-buy)

btw: Love the tool

**Comment by GoldenGnu** [comment]
That is already possible:
![active_orders_count](https://user-images.githubusercontent.com/11528122/87851682-5b294800-c8fb-11ea-8041-89511ed90023.png)
_Showing **X** of X_ is the row count.
Will that fit your needs?

**Comment by chatelao** [comment]
Uh, great. Thank you
