### ISSUE TITLE
Market Orders - Outbid Range setting

### ISSUE THREAD

**Issue by Sardaukai** [GoldenGnu/jeveassets#170]
Hi,

as discussed at discord my post for this issue.

It is not possible to filter the range of possible outbids at Market Orders.

i.e.:
You sell an Item at a null Citadel with market and you only want to check prices within the system (Filter System - Sell) all outbids within region will be displayed. I have tried all possible drop down values (Station / ?? Jumps)

I am not able to test that at not null space! Maybe it works in the empire

**Comment by GoldenGnu** [comment]
Released in 6.5.0
