### ISSUE TITLE
JWT is null

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#171]
From the update menu, under character, all of my characters receive this message.

ESI > Account > CharacterName
JWT is null

What am I doing wrong?

**Comment by GoldenGnu** [comment]
Only thing you can do is edit the accounts, to re-auth. I’m not sure why this happened. But, if you transferred the character or changed the password, that will invalid all SSO auth.

**Comment by GoldenGnu** [comment]
Released in 6.5.0
