### ISSUE TITLE
JWT is null, Error code 403

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#174]
In version 6.5.0, when I update I receive multiple errors in accounts, data, dynamic, and contract items.

### In ACCOUNTS we have multiple instances of the following:

> ESI > Account > CharacterName
> JWT is null
> 

### In DATA we have we have multiple instances of the following:

> ESI > Account Balance > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Market Orders > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Assets > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Journal > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401
> 
> ESI > Industry Jobs > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Contracts > CharacterName
> {"error":"This software has exceeded the error limit for ESI. If you are a user, please contact the maintainer of this software. If you are a developer/maintainer, please make a greater effort in the future to receive valid responses. For tips on how, come have a chat with us in #esi on tweetfleet slack. If you're not on tweetfleet slack yet, you can get an invite here -> https://www.fuzzwork.co.uk/tweetfleet-slack-invites/"}
> 
> ESI > Blueprints > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Bookmarks > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 

### In DYNAMIC DATA we have we have multiple instances of the following:

> ESI > Active Ship > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Planetary Assets > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 
> ESI > Locations > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 

### In CONTRACT ITEMS we have we have one instance of the following:

> ESI > Contract Items > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
> 

Also, MARKET PRICES failed to update market data, there was no further explanation.

### When updating STRUCTURES we receive multiple instances of the following:

> ESI > Structures > CharacterName
> Error Code: 403
> {"error":"unexpected end of JSON input","sso_status":401}
>

**Comment by GoldenGnu** [comment]
ACCOUNTS:
I have no clue, why that is happening, but, please, email me the log: 
https://jeveassets.nikr.net/faq#bugs
As I wrote in your last bug report:
It's unable to get an access_token, so, I think the only way to fix it, is to edit the affected accounts:
Options > Accounts... > Edit

DATA/DYNAMIC DATA/CONTRACT ITEMS:
It's the same error as the accounts one - It's missing authentication so, it can't update from authed endpoints.

MARKET PRICES
https://evemarketer.com is currently offline, that is why that doesn't work.
Options > Options... > Market Prices > Price Source > fuzzwork.co.uk

**Comment by brightvalley** [comment]
Log sent.

**Comment by GoldenGnu** [comment]
@brightvalley 
Can I consider this resolved?

**Comment by brightvalley** [comment]
I did send you the logs you requested, didn't I? If not I apologize and
I'll send them again.

**Comment by GoldenGnu** [comment]
You did, and I walked you trough how to fix it. Are you still having this problem?

**Comment by FireCulex** [comment]
Just came across this error.  Had to go through 12 chars and reauthorize them all to fix it.

**Comment by GoldenGnu** [comment]
This issue is not fixable, it's simply due to the refresh token no longer working.
I have made a new issue for improving the error message (the current one is amazingly bad):
https://github.com/GoldenGnu/jeveassets/issues/193
