### ISSUE TITLE
Unable to delete/edit stockpile entries

### ISSUE THREAD

**Issue by Nickand87** [GoldenGnu/jeveassets#176]
With the current update today I am unable to edit, clone, delete, nor add new items to most stockpile entries.  The ones closer to the top are still editable and etc, but as I move down the list and as time goes by fewer and fewer are editable.

**Comment by GoldenGnu** [comment]
Thank you for your bug report.
I will be releasing a bug fix version later today.

**Comment by GoldenGnu** [comment]
Released in 6.5.1
