### ISSUE TITLE
Find out how many slots you have free with my characters

### ISSUE THREAD

**Issue by shutupandshave** [GoldenGnu/jeveassets#179]
I'd like the industry tab to have the ability to let me know how many slots my chars have, and how many are in use.
I.E.

![image](https://user-images.githubusercontent.com/918561/88462353-aebf0700-cea2-11ea-86e5-bc8083a680a0.png)

**Comment by GoldenGnu** [comment]
I really like the idea. I'm sure a lot of people would find it useful.
I'm going to plan it for the next feature release, but, it may be moved to a later release, if it turns out it's complicated to do.

**Comment by GoldenGnu** [comment]
Released in 6.6.0
