### ISSUE TITLE
Split assets name column into two columns: type and item name

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#181]
It's a small change, but for various things in the inventory list, principally ships but other things too, the name of the item is followed by the type of thing it is in parentheses. For instance, "Some Ship Name (Orca)".

Would there be any benefit to adding another data field, called Type or something similar, immediately after Name, which will contain the text you are currently placing in the parentheses? For example, "Orca" from the example above. If the ship had no assigned name then the name field would contain the ship type (as it does now) and the Type field would follow with the item type.

What do you think?

**Comment by GoldenGnu** [comment]
If there should be two columns, I think one should be the type exclusively and the other should be the name of the items (for the items that have names). But, I do not really see any advantage of have two columns.

What would the use case be, that require two columns?
If there is reason to do it, it won't be a lot of work to do it, but, on the other hand if there is not a strong argument to do it, I would rather use my free time to code something that adds new functionality.

**Comment by brightvalley** [comment]
Principly because it makes those items with a type sortable (and
searchable). For instance, an industrialist could sort on "destroyer" and
pick out from the collection of destroyers they've warehoused where all his
Cormorants were located, or they can sort on Type and see all the
Cormorants at one time. It separates the name of an item from the type of
item it is.

**Comment by GoldenGnu** [comment]
That makes sense.

**Comment by brightvalley** [comment]
I wouldn't consider it a high priority. If you have things to fix , and who
doesn't, then save this for a rainy day.

**Comment by GoldenGnu** [comment]
Released in 7.0.0
