### ISSUE TITLE
Feature: Make skill points optional

### ISSUE THREAD

**Issue by Bonsailinse** [GoldenGnu/jeveassets#187]
Hey!
I generally like your addition of skill points to your software, but I would love to have them not appear in some places without me being able to exclude them.
In particular the "Isk" tab is rendered useless if you want to have a quick overview over your liquid-ish assets and wallets but have no intention to ever make skillpoints into ISK.
I would love to have an option to toggle it somewhere, thanks!

Keep going and stay safe o/

**Comment by GoldenGnu** [comment]
Released in 6.6.1
