### ISSUE TITLE
The browse action is not supported

### ISSUE THREAD

**Issue by sjukfan** [GoldenGnu/jeveassets#19]
jEveAssets 5.0.0
openjdk-9
openbox as wm

When I try to add an ESI account I get a
> ERROR: [AWT-EventQueue-0] net.nikr.eve.jeveasset.io.esi.EsiAuth - The BROWSE action is not supported on the current platform!

Would it be possible to add the possibility to copy and paste the url to the browser of choice?

**Comment by GoldenGnu** [comment]
Would adding the url directly to the clipboard be a viable solution for you?
It's a little bit easier to do, than making a GUI for it.

I will try include this in the next bug fix release. I'm hoping to release it over the weekend...

**Comment by sjukfan** [comment]
Yeah, url to clipboard is fine. If it's not too much work, maybe a linky clicky thing so people who don't want it in their clipboard don't get it. Could be just a link in the help text.

**Comment by GoldenGnu** [comment]
I will make copying the URL to the clipboard optional.
I have done most of the work on this and hope to finish it today.

**Comment by GoldenGnu** [comment]
This is now released. I going to close the issue, please, comment here if you can not get it to work, I will re-open the issue.
