### ISSUE TITLE
jEvEAsset 6.7.0 DEV Build 1 - Issue Error Code 500

### ISSUE THREAD

**Issue by Sardaukai** [GoldenGnu/jeveassets#197]
Hi,
I realized some huge gap's between assets ingame and jeveasset.  (Chromium 50k vs 13k)
I saw this error code while updating assets (send you a log file)
 
I tried to downgrade to different versions of jeveasset with the same result.
Then i tried to upgrade to the new dev build, same.
 
 
I hope it is not a big think and you are able to solve the problem.
If you need someone to test, tell me what I can do.
 
 
Sardaukai

**Comment by GoldenGnu** [comment]
Thank you for your bug report.
It’s an ESI error:
https://github.com/esi/esi-issues/issues/1240
There is nothing I can to make it work.
CCP is aware of the bugs severity but, haven’t had the time to fix it yet.

**Comment by GoldenGnu** [comment]
@Sardaukai 
I fix have been deployed by the ESI devs. If you could reply here or by email, to validate that it is indeed working again, that would be a great help for me and the ESI devs, thanks.

**Comment by Sardaukai** [comment]
It should work with that fix again - I checked some numbers - all fine

**Comment by GoldenGnu** [comment]
Thanks for reporting back, I will let the ESI team know

**Comment by GoldenGnu** [comment]
Released in 6.6.3
