### ISSUE TITLE
Add Character Mining Ledger

### ISSUE THREAD

**Issue by douglas24** [GoldenGnu/jeveassets#20]
Please add Personal/Corporate Mining Ledger API endpoints once they are published.

**Comment by GoldenGnu** [comment]
I may do this in the future, but, all my time is used fixing bugs at the moment. So, this feature will not be in jEveAssets for some time.

However, this feature will be in Evernus very soon:
https://forums.eveonline.com/t/evernus-2-15-release-the-ultimate-market-tool/6031/92

**Comment by GoldenGnu** [comment]
- [x] Personal mining log
- [ ] Graph
  - Filters
    - [ ] Date (to/from)
    - [ ] Type
  - Data
    - [ ] Quantity
    - [ ] M3
    - [ ] Isk
- [ ]  Corporation mining log
  - Require a corporation with refineries to help test it

**Comment by GoldenGnu** [comment]
Released in 7.6.0
