### ISSUE TITLE
Memory Optimisation Issue with the Market Order Tool

### ISSUE THREAD

**Issue by madPac34** [GoldenGnu/jeveassets#203]
When you open the Market Order Tool and do a market update the memory usage expectedly goes up, but then when another update happens it goes up again and seemingly does not overwrite the old data. With 3+ updates it does not change 

After 1 market update - 1450mb
After 2 market updates - 1900mb

Just seems a bit off or inefficient

**Comment by GoldenGnu** [comment]
It’s unlikely there is a memory leak if the usage stabilize after 3 runs. It’s far more likely that you have plenty of free memory, so, Java doesn’t use any unnecessary CPU cycles on freeing memory.

If you want to understand how Java memory management works you can look up Java garbage collection and Java heap, as it’s dynamic process.

I will ofc. profile to make sure! 👀
