### ISSUE TITLE
Shortcut for opening Eve Market UI

### ISSUE THREAD

**Issue by rpoplawski0** [GoldenGnu/jeveassets#205]
Hi
As it is now, to open Eve ingame market menu you have to:
- right click on the order
- Eve UI
- Market
- confirm the character (even with only one char configured in jeveassets)
- close confirmation popup

Is it possible to add a shortcut (something like CTRL-mouseclick) to skip all those steps and open the market menu directly?

Thank you for the fantastic software!

**Comment by GoldenGnu** [comment]
Any reason why you're not using the Open button in the table?
![open_market_order](https://user-images.githubusercontent.com/11528122/97705453-6a9c5d80-1ab4-11eb-8c9f-7c96e91d215b.png)
It have the added bonus, that if you're underbid, it will copy a fixed price to the clipboard.

**Comment by rpoplawski0** [comment]
I have no idea how I missed this!
That column was hidden for me. It works exactly like what I asked for.
Thank you:)
