### ISSUE TITLE
Feature request: Lock Start System in route planner

### ISSUE THREAD

**Issue by inkogandersnito** [GoldenGnu/jeveassets#209]
Example
Filters: 0.5 - 1.0
A couple of systems added are in low sec. This will generate "There is no route between X and Y". After removing Y from the list of systems you have to select X as Start System again.

In a long list of systems where more than a handful having no route it would be helpful to "lock" the Start System. The field that shows Start System can be made a little shorter to make place for a checkbox.

**Comment by GoldenGnu** [comment]
I can see why that would be annoying.

**Comment by GoldenGnu** [comment]
Released in 6.7.0
