### ISSUE TITLE
Include hidden stockpiles in Export

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#211]
When exporting stockpiles (as an XML or text) and selecting which stockpiles to export, only the visible ones are listed and selectable. While that may be useful, it would also be nice to have an "list hidden stockpiles" option, in case we want to export stockpiles that are currently hidden.

I have over a hundred stockpiles and I use the hidden/visible status to determine which ones are currently in use, but when I'm exporting (for backup or transfer to another machine), it gets quite annoying to restore which ones were hidden or not afterwards.

**Comment by GoldenGnu** [comment]
Released in 6.7.0
