### ISSUE TITLE
404 on update: journal/transactions/account balance

### ISSUE THREAD

**Issue by Liiloue2020** [GoldenGnu/jeveassets#212]

**Comment by GoldenGnu** [comment]
What error message are you getting?
The wallet endpoints (journal/transactions/account balance) have been experiencing problems for the last 3 days, so maybe that is the problem?
The ESI devs have been notified, so there is nothing else I can do.

**Comment by Liiloue2020** [comment]
Hello, yes it’s the same problem i have
Ty for repply

Envoyé de mon iPhone

**Comment by GoldenGnu** [comment]
ESI issue: https://github.com/esi/esi-issues/issues/1256
