### ISSUE TITLE
ESI error

### ISSUE THREAD

**Issue by Enthargo** [GoldenGnu/jeveassets#213]
When ever I update i get this error for Data. Also the wallet balance isnt correcting and shows zero, when its not.

ESI > Account Balance > Tina Niam
Error Code: 404
{"error":"Not found"}

ESI > Journal > Tina Niam
Error Code: 404
{"error":"Not found"}

ESI > Transactions > Tina Niam
Error Code: 404
{"error":"Not found"}

**Comment by GoldenGnu** [comment]
Same as #212
