### ISSUE TITLE
Heavy use of CPU when idle

### ISSUE THREAD

**Issue by AdamAntinoo** [GoldenGnu/jeveassets#214]
Latest version 6.6.3 consumes a whole CPU continuously even if the user is not interacting with the tool UI.

I have disabled the option 'focus'Eve-Online after opening in game windows' but this has not changed the CPU usage.

Kind regards

**Comment by GoldenGnu** [comment]
This is most likely due to high memory usage.

First make sure you're using the 64bit version of Java.

If that does not fix the problem, you have to use jmemory (see the wiki for [details](https://jeveassets.nikr.net/jmemory)).

**Comment by GoldenGnu** [comment]
No additional input from the users
