### ISSUE TITLE
As complete a restore at relaunch as possible, please

### ISSUE THREAD

**Issue by Pure-Blind** [GoldenGnu/jeveassets#216]
I don't quit jEveAssets as often as I should for updates, due mainly to the time consumed "reconfiguring" it after each launch.
What I'd like, as much is possible, is for it to start up again **exactly** where I left it.
In my particular case (I daresay there are others), I have to do the following...
(Tabs are restored, so that's good)...
Transactions - reload my filter - yes, there's a Save and Load for those, but the blank line I like to have below my "Last 15 days" doesn't get restored.
Transactions - I do exports, but the "current filter" radio, that I always want, isn't saved - it's a very very big file for the subsequent import if I forget to do this
Tracker - I have to set this to one week each time. I also have to turn off "skill points"
Contacts - I have always to set this to ("in progress" or "outstanding")
ISK - I have always to uncheck "Show", to get myself more visible on the list, since I never use filters on this tab.

I admit - none of this is critical, programming breaking stuff - it will just save me (and I'd guess others), some time. Perhaps I'm spoilt being a Mac user (maybe Windows does this too, I have no idea) - I can quit Numbers, for example, and when I relaunch it I'm back exactly where I was - the things I had open are re-opened, the unsaved sheets too - in their previous window positions, with the last configuration tab I was using pre-selected - like I'd never quit.

o7

**Comment by GoldenGnu** [comment]
Save on exit, load on startup
- Filters
  - Current filter
  - Save empty filters?
  - Show/Hide filter panels
- Export settings
  - Filter setting (current/selected/none)
- Tracker
  - Showed lines

Re: Tracker, you're probably better of using the permanent filter, by clicking the Skill Point Filters and unchecking everything.

**Comment by crmason2** [comment]
@GoldenGnu I'm working on this currently

**Comment by crmason2** [comment]
Current Progress Completed.
Filters
-Save Current Filters for restore at load
-Save Empty Filters and Disabled Filters, for current filter, save, load, import and export
-Save Show/Hide Filters, for current filter, save, load, import and export

**Comment by crmason2** [comment]
Current Progress Completed.
Export Settings (for each tab)
- All exports types individual settings
- View selection
- Column selection
Tracker
-Showed lines
-Date ranges
-Linear or Logarithmic
-Include Zero

Have some minor refactoring left before submitting a PR. Want to pull additional settings for the track from Settings.java into TrackerSettings.java

**Comment by GoldenGnu** [comment]
Released in 6.9.0
