### ISSUE TITLE
khon.space is retiring - update the URL to use the new one

### ISSUE THREAD

**Issue by Kyria** [GoldenGnu/jeveassets#217]
Hello,

[As I have posted in the EVE forum](https://forums.eveonline.com/t/lazyblacksmith-khon-space-shutdown/285537), khon.space is retiring, and if i'm not mistaken, you use it in jEveAssets. 

The new URL is https://lazy-blacksmith.space 

There's currently a redirection to avoid breaking bookmarks, app links etc (which will last at least 1 month without issue) but don't forget to update your app :)

**Comment by GoldenGnu** [comment]
Thank you for making an issue for it.
I did see the forum thread and was already planning to fix it for the next release.

**Comment by GoldenGnu** [comment]
Released in 6.7.0
