### ISSUE TITLE
Journal page doesn't appear to show transactions from Hypernet Relay

### ISSUE THREAD

**Issue by DynoEnviro** [GoldenGnu/jeveassets#218]
'Completed Hypernet Relay Payout'
'Hypernet Relay Fee'

These transactions are shown on the wallet Transaction tab in-game.

**Comment by GoldenGnu** [comment]
@DynoEnviro 
Thank you for your bug report.
It's most likely a ESI issue. I will try to get a ESI issue made so it can be fixed.

**Comment by crmason2** [comment]
@GoldenGnu can confirm that Hypernet transactions are not in the ESI wallet response.

**Comment by GoldenGnu** [comment]
@crmason2
If you're up to it, I could use the following to create an ESI bug report:
- In-game screenshot of the journal entry and the entries before/after
- Raw response and headers (easiest with the [web ui](https://esi.evetech.net/ui))
Both should censure out Intel stuff...
Or if you like you can make the ESI bug report yourself.
If you're not up for it, that is perfectly fine too :)

**Comment by crmason2** [comment]
Bug report opened with CCP.
Issue ID: EBR-213665

**Comment by crmason2** [comment]
@GoldenGnu say you created a public issue under the esi repo. I'm going to link it here for traceability.  esi/esi-issues#1171

**Comment by GoldenGnu** [comment]
Thanks. I forgot about that 🤔

**Comment by GoldenGnu** [comment]
I tried to push for a bug fix, but, it doesn't looks like this in line to be resolved. I will keep trying to push the issue once in a while.

**Comment by GoldenGnu** [comment]
Released in 7.0.0
