### ISSUE TITLE
Feature Request: Add 'Value', 'Margin', and 'Profit' Columns to Market Order list

### ISSUE THREAD

**Issue by crmason2** [GoldenGnu/jeveassets#221]
Add 'Value', 'Margin', and 'Profit' columns to the Market Order screen to allow analysis of expected returns based on target markets. This will use the Options -> Market Prices as the bases for comparison.

**Comment by crmason2** [comment]
Making changes based on Discord discussions with @GoldenGnu will resubmit after committing changes.

**Comment by GoldenGnu** [comment]
Released in 6.7.0
