### ISSUE TITLE
Bug:  Outbid # showing incorrect value after market orders update

### ISSUE THREAD

**Issue by crmason2** [GoldenGnu/jeveassets#226]
The count of the Outbid # column seem to lag behind on updates. I have seen examples where on buy orders Outbid $ was green (indicating it that your price was the highest) yet the Outbid # was >0 which indicates there are that many order above yours. Both can not be true and after looking at the market data as well as in game data the Outbid # was inaccurate. After testing it seem like the Outbid number is being calculated using the previous updates data and no the current one.

**Comment by crmason2** [comment]
@GoldenGnu you can assign this issue to me.

**Comment by GoldenGnu** [comment]
I was going to take a look at this too, as I suspect it's the comparison between the old not-update price of the market order that make it green, but, still have a count.

But, I think it's fine you investigate as well

**Comment by GoldenGnu** [comment]
Released in 6.7.0
