### ISSUE TITLE
Import into existing Stockpile

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#228]
The Import feature for Stockpiles is great, for turning an EFT fit or a Multibuy list into a Stockpile. It however only lets you create a new Stockpile from it, but it would be very useful to be able to import into an existing stockpile.

**Comment by ImperialStarkDestroyer** [comment]
+1 from me too :)

**Comment by GoldenGnu** [comment]
- [ ] Xml
  - [ ] Import unchanged (same name)
  - [ ] Create new stockpile
  - [ ] Add items to stockpile(s)
  - [ ] Ignore/skip/cancel
- [ ]  Text
  - [ ] Create new stockpile
  - [ ] Add items to stockpile(s)
  - [ ] Cancel

**Comment by GoldenGnu** [comment]
Released in 7.5.0
