### ISSUE TITLE
System and Constellation Column

### ISSUE THREAD

**Issue by alexthefoxeve** [GoldenGnu/jeveassets#229]
Please add Columns for System and Constellation

**Comment by GoldenGnu** [comment]
In what tools do you need those columns?
Also, I'm curious, what is the use case for those columns?

**Comment by alexthefoxeve** [comment]
at the moment I have some filters preset to filter for the constellation I am living in, so it works for me, but would smoothen things a bit. 
Could be interesting for people/corps living in highsec pocket constellations such as Mayonhen.

**Comment by GoldenGnu** [comment]
Thank you for explaining the use case, that really helps to understand how this feature is useful.
The constellation data is not currently in the jEveAssets data files, but, it's it shouldn't be too hard to add

**Comment by shutupandshave** [comment]
This would be useful to have on the industry page as well, so I can see which characters are near to where I build.  IDEALLY I could input a home system and it would also tell me which characters are in range to build/research/react.  That said, just their location would be a great start.

**Comment by GoldenGnu** [comment]
Support for constellation have been added to https://github.com/GoldenGnu/jeveasset-creator
But, not in jEveAssets. yet.

**Comment by GoldenGnu** [comment]
Constellations data are now in jEveAssets (on the feature branches).
But, it have not been added to any columns, yet.

**Comment by GoldenGnu** [comment]
Working on this now

**Comment by GoldenGnu** [comment]
ToDo:

- [x] Assets
- [x] Tree
- [ ] Transaction
- [ ] Market Orders
- [ ] Industry Jobs
- [ ] Overview
  - In progress
- [ ] Stockpile
- [ ] Industry Slots
- [ ] Isk

**Comment by GoldenGnu** [comment]
Released in 6.8.0
