### ISSUE TITLE
Reactions - Can we get the value for reactions jobs in progress like we do manufacturing jobs?

### ISSUE THREAD

**Issue by jonjo179** [GoldenGnu/jeveassets#23]
title

**Comment by GoldenGnu** [comment]
This should already be done in 5.1.0? it does require you update to the latest data version too.

Could you post a screenshot of your reactions?

To anonymize the screenshot do the following:
1) Right click anyway in the Industry Jobs table
2) Select Columns > Columns...
3) Uncheck: Owner, Installer, Location, Region
4) Press OK

**Comment by jonjo179** [comment]
https://imgur.com/a/3K4Ea

These are corp jobs and the client is updated. First screenshot shows reaction BPs only not the reaction items.

**Comment by GoldenGnu** [comment]
Thank you for your answer :)

I looked at the code and the output from Industry Jobs are not included in Assets.
Only the blueprints in Industry Jobs are added to Assets.

The output value/count is included in the Industry Jobs tool and you can also create stockpiles with manufacturing (that include reactions), that will count the output

Should I consider this a feature request to include manufacturing/reactions output to the Assets tool?

**Comment by jonjo179** [comment]
Manufacturing job outputs in progress are (or were) included in assets list so would be nice.

Currently are Reaction outputs included in total asset valuation? To me thats the most important thing.

**Comment by GoldenGnu** [comment]
Manufacturing and reactions are included as Manufacturing in both the Tracker and Isk tools.

I have create issue #25 for adding manufacturing and reactions to the assets tool.
No promises on when I will get the time to do it, but, it will get done at some point in the future.
