### ISSUE TITLE
Font really looks bad on Arch Linux

### ISSUE THREAD

**Issue by epixinvites** [GoldenGnu/jeveassets#233]
https://imgur.com/a/0E6Fszz

The font really looks bad and its too small and it really hurts to just look at it.

**Comment by GoldenGnu** [comment]
If you’re on a 4K monitor, you could try the following workaround: https://github.com/GoldenGnu/jeveassets/issues/11
If you’re not on a 4K monitor, or the workaround does not work, I will need the know the Java version and if it’s OpenJDK, Oracle, or Arch’s own distribution, so I can test it myself. It would also be useful to know what version of Arch you using, as well as the desktop manager.

**Comment by epixinvites** [comment]
Ok, so I'm just on a normal 1920x1080 computer, 
java --version returns: 
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

**Comment by GoldenGnu** [comment]
Thank you for the version info. I haven’t had time to test this out and won’t have time week, but, I will test it as soon as I have the time.

in the meantime please try the following workarounds from the arch wiki:
https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts

**Comment by epixinvites** [comment]
Ok so my UI looks 100x cleaner and more beautiful after installing xsettingsd, apparently after some reading I found out that i didn't even have a settings daemon, which probably makes sense since I didn't even install any desktop environments. Thanks :) I'll make this issue as solved.
