### ISSUE TITLE
Suggestion: Let us have a way to run it in the background and turn off those pop-ups

### ISSUE THREAD

**Issue by epixinvites** [GoldenGnu/jeveassets#234]
It's probably useful for those who has JEveAssets running all day (like me) and when I'm writing some code halfway the Market Auto-Update pop-up just appears suddenly which is really annoying.

**Comment by GoldenGnu** [comment]
Could you share a screenshot of the popup? If you enable Outbid auto update, nothing should be popping up. Even on error, it should just log it

**Comment by epixinvites** [comment]
Yes I enabled auto-update but right after the auto update theres pop up for like a second which i think says "Processing" and a blue thin bar and disappears almost immediately.

**Comment by GoldenGnu** [comment]
The dialog is required, as it locks jEveAssets while the update is applying, it can't be avoided.
It's just a simple way to locking the user interface.
I tried it on windows and it does not go in front of any programs I'm using.
It stays in the background, if jEveAssets is in the background. It also stay hidden if jEveAssets is minimized.
Could you try minimizing jEveAssets and see if the dialog still shows?

**Comment by epixinvites** [comment]
I run on arch and I use i3 (did mention in the previous issue few days ago) so I have jeveassets in an idling workspace all the time.

**Comment by GoldenGnu** [comment]
And it still popup on your main desktop?

**Comment by epixinvites** [comment]
Yes it does.

**Comment by epixinvites** [comment]
I'll just close this issue since its just idling there.
