### ISSUE TITLE
Additional shopping list options for Stockpiles

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#235]
When generating a shopping list for stockpiles, it only lists whatever is missing from these stockpiles, which is in almost all cases what you need. 

There are however some cases where you'd want to see the full list regardless of what assets you may already have, or just what you actually already have.

It would be nice to have some checkboxes when generating a shopping list to decide whether to include owned assets or missing assets (or both).

**Comment by GoldenGnu** [comment]
Added options:
-Items Missing (works like the current shopping list)
-Items Required (Items needed by the stockpiles)
-Items Owned (Items owned matching the stockpiles)

**Comment by GoldenGnu** [comment]
Released in 7.0.0
