### ISSUE TITLE
"Industry Slots" won't save/load my Filters

### ISSUE THREAD

**Issue by alexthefoxeve** [GoldenGnu/jeveassets#242]
Greetings,

the "Industry Slots" tab will let me save my filters, but on closing and opening jEveAssets, the saved filters won't be loadable anymore.

Thanks for your hard work.

**Comment by GoldenGnu** [comment]
Thank you very much for the bug report!
The bug have been found and fixed and will be included in the next release.

**Comment by GoldenGnu** [comment]
Released in 6.8.0
