### ISSUE TITLE
"Copy", "Paste", "Cut", "Select All" shortcuts on a Mac

### ISSUE THREAD

**Issue by Pure-Blind** [GoldenGnu/jeveassets#243]
Can we please have these mapped to the "native" Mac shortcuts using "command", and not "control".

Thanks

o7

**Comment by Pure-Blind** [comment]
Specifically...
Cut - <command>+x
Copy - <command>+c
Paste - <command>+v
Select All - <command>+a
Undo - <command>+z
Redo - <command>+<shift>+z

**Comment by GoldenGnu** [comment]
Released in 6.8.0
