### ISSUE TITLE
Behaviour when adding new filter line...

### ISSUE THREAD

**Issue by Pure-Blind** [GoldenGnu/jeveassets#245]
...is "strange" shall we say :-)

Example 1...
So I'm on Market orders and I load in my filter of 2 lines...
* Type Equals Buy
* Status equals Active

I want to add on another filter so I click the little Add Filter button - a new filter is created, and the initial set up of that filter is COPIED form the line above.
I can't be the only person for whom this is never never EVER what I want.
In the case I describe above, I'm wanting to now add a filter for a particular item - ie ...
All Contains <empty search>

Example 2...
I'm on Transactions, loaded with my "last 15 days" filter.
Of course, I now want to add my "All Contains <empty search>" to narrow it down, but adding a new filter row duplicates the "last 15 days" - again, not ever ever what I want to do.

I tried saving my filters above to include the "empty" "All Contains" line, but that isn't saved when saving a filter set.

I propose...
1) Creating a new filter creates the "default" filter - the one you get when you launch jEveAssets - normally this is "All Contains <empty search>" - this seems to me to be natural and, I hesitate to say, what a user would expect.
2) That filter sets ARE saved with any "empty lines", if you'd specified them - again, it's what you'd expect - for save to save what's there, shown, visible, regardless of whether you've entered a value in to the actual search part of the field yet.
3) While you're there, I think "All" should be renamed "Any" since, well, it's any rather than all.

o7

**Comment by GoldenGnu** [comment]
It's explained here:
https://jeveassets.nikr.net/manual/filters
In short, clicking the small button on the filter line, copies the filter. Clicking the `Add` (with a green plus icon) on the above toolbar adds an empty filter line

**Comment by Pure-Blind** [comment]
Stupid Me.
2 and 3 aren't invalid though?
Or how DOES one save a blank line in a saved filter?

**Comment by GoldenGnu** [comment]
2) Please make a new issue for it, have more than one problem in each issue get confusing. It have been asked before, so, I will consider it valid.

3) I’m not sure what the grammatical difference is here. All meaning: matching all columns. I’m not sure it’s a good idea to change it now, since people will get confused about the name change.

**Comment by crmason2** [comment]
For number 2 that will be addressed in Issue #216 which is currently in progress.

**Comment by GoldenGnu** [comment]
Closed in favor of #216
