### ISSUE TITLE
Broker fee does not get incremented with market changes

### ISSUE THREAD

**Issue by ExcavatorOnatop** [GoldenGnu/jeveassets#249]
JEveAssets has Auto Update on, the edits of a sell market order reflect the number of edits correctly, but the broker's fee is unchanged. For example, check the Compressed Scordite order (highlighted):
<img width="1652" alt="Screen Shot 2021-04-09 at 1 33 08 PM" src="https://user-images.githubusercontent.com/82235167/114225618-28ffc080-9938-11eb-8b3c-a9b62cb8da1c.png">

now, I am going to change the same order again, notice that the edit number is 4 now, but the broker's fee is unchanged:
<img width="1367" alt="Screen Shot 2021-04-09 at 2 04 32 PM" src="https://user-images.githubusercontent.com/82235167/114228890-b7764100-993c-11eb-9fd3-7e8b0a54feae.png">

**Comment by GoldenGnu** [comment]
I'm not able to reproduce this. As soon as the broker fees are included in the journal, they're also included in the broker fee column.
Ofc. they won't be include until the journal is updated.
If you have any extra step that helps reproduce this, please, let me know and I will reopen the issue.
