### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TRIONI995** [GoldenGnu/jeveassets#251]
Hello. I need your help in implementing a project to track corporate assets and build an online graph on the site. Please call me Robert Downey Jr. # 0915

**Comment by GoldenGnu** [comment]
I already have enough work.
So, I will have to redirect you to the ESI documentation:
https://github.com/esi/esi-docs
if you have questions, you best bet it to join the twitterfleet slack. But, don’t expect people to answer everything. You need to describe your problem well to get an answer. General questions will most likely not be answered.
Good luck, ESI can be really fun to work with.
