### ISSUE TITLE
Stockpile: Transactions Price + Market Details columns

### ISSUE THREAD

**Issue by NordicSurvivor** [GoldenGnu/jeveassets#256]
Hello
here a please / suggestion. Possibly also helpful for others.
Is it possible to add a column in the "Stockpile" tab that shows the average price of the item from the "transactions" tab. And what else would be good. Also add the button "Market Details" open "in the" Stockpile "tab. So you can jump directly to the buy / sell window in the EVE Client from the Stockpile tab. This is already possible by the right click menu but with the button this would be a bit win :) 

Thank you very much for the great work I love it

**Comment by GoldenGnu** [comment]
Average transactions: The average should include both sell and buy transactions.
Not that it may be useful to use the same settings as transaction prices (age/price type)

A button column should be really easy to add.

**Comment by GoldenGnu** [comment]
- [x] Market Details column
- [ ] Transactions Price column

**Comment by GoldenGnu** [comment]
Released in 7.0.0
