### ISSUE TITLE
Pressing SHIFT+2 in a formula crashes jEveAssets

### ISSUE THREAD

**Issue by ericjeker** [GoldenGnu/jeveassets#260]
When editing a formula, put the caret in the formula field, press SHIFT+2 (on my keyboard it create the quote symbol `"`). This crashes jEveAssets. Probably because it's not an allowed character? I tried with other characters but it doesn't crash.

I use version 6.9.0.
Bug is 946 I think.

**Comment by GoldenGnu** [comment]
Could you post what was in the formula field before entering the `"`?
It would really help reproduce the problem and fixing it.

**Comment by ericjeker** [comment]
There is nothing in the formula. I just open the Formula window, click in the Formula field, and press `SHIFT`+`2`, which on my keyboard creates a quote sign.

**Comment by GoldenGnu** [comment]
Thanks! Are able to reproduce with version 6.9.1?

**Comment by ericjeker** [comment]
It seems to be fixed in 6.9.1! Magic! :-)

**Comment by GoldenGnu** [comment]
Thank you very much for verifying the fix! :)
