### ISSUE TITLE
The Formula of the Formula Column is applied to the "Total" line

### ISSUE THREAD

**Issue by ericjeker** [GoldenGnu/jeveassets#261]
Funny "bug":

![image](https://user-images.githubusercontent.com/979397/121852403-061bcf00-cd22-11eb-99ba-c70a89dd0399.png)

The Total Line should do a sum of the column and not apply the same formula to the Total Line. 
In the example above I do `[Target ×]*[Price]`.

**Comment by GoldenGnu** [comment]
I agree, It's reasonable to assume people want the total here.
However, it's not a simple fix, so, it likely won't be in the first round of fixes.

**Comment by GoldenGnu** [comment]
Released in 6.9.3
