### ISSUE TITLE
Feature request: Open ship fitting from assets tool

### ISSUE THREAD

**Issue by packetizeme** [GoldenGnu/jeveassets#264]
I only recently discovered the use of the "ship fittings" tool, but it's been quite useful (thank you)!

It would be nice if selected assets (in the assets window), when they are unpackaged ships, could be opened directly into the ship fittings tool. At the moment if I want to be sure I'm looking at the right thing I scroll over to the ItemID column and then match that (by eye) with the ID presented at the end of the ship selection in the fittings tool.

As an alternative it would also be helpful if ship fittings allowed for filtering such that one could paste the appropriate Item ID as a filter.

**Comment by GoldenGnu** [comment]
- [x] JMenuLoadout open ship on Loadout tool from Assets or Tree tool
- [ ] AutoComplete (strict) for Loadout ship ComboBox

**Comment by GoldenGnu** [comment]
I added a table menu to select a ship in the Fitting Tool from the Assets and Tree Tools
I also tested filtering on the ship JComboBox, but, didn't work well, so, that will not be included.

**Comment by GoldenGnu** [comment]
Released in 7.0.0
