### ISSUE TITLE
Feature Request:  Market Orders - Highlight Recent changes

### ISSUE THREAD

**Issue by Count0Int** [GoldenGnu/jeveassets#265]
It would be nice to have some method of displaying when a market order has changed recently, primarily interested in the 'quantity remaining'.  I think this is something Evernus had?  Correct me if wrong.

Ideally, have the 'highlight' or whatever method of showing display until a 'clear changes' button was pushed...

Cheers!

**Comment by GoldenGnu** [comment]
Similar to #269

**Comment by GoldenGnu** [comment]
Released in 7.0.0
