### ISSUE TITLE
Stockpile Contracts: Match All

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#266]
It would be useful to be able to have a a stockpile for example a 'imported eve fit' to have a check box or setting in the stockpile settings that makes it so it will only search for exact matches. Example if I have 10 Retributions and 10 Manticores and both share nanite paste but only 9 of 10 retributions are listed and all 10 manticores it will show that the retributions have nanite paste stock which would be incorrect because it does not.

I searched the eve API and see that the contract API only returns a list of items back and does not designated if they are fitted or not to the ship.  The only solution I could imagine is a option to check for the stockpile which makes it search for all items matching with quantities matching to be considered in stock.  Please see our previous Discord conversation for more information starting at this link https://discord.com/channels/565306310229229569/565306310229229571/878867582797623337.

**Comment by GoldenGnu** [comment]
Released in 7.4.0
