### ISSUE TITLE
Transaction / Journal New Column - "New Since Last Update"

### ISSUE THREAD

**Issue by tiedyedguy** [GoldenGnu/jeveassets#269]
Could we get a column that shows if something is new from the last update in the "Transaction" and "Journal" area.

Other areas might make sense but those are the only ones I use :)

**Comment by GoldenGnu** [comment]
One options is saving the date of the newest transaction/journal before updating and highlighting newer data in the table.
And either a button clear new entries or simple reset on update?
Similar to #265

Alternative, add the last-modified date to the data and display that in it's own column.

**Comment by tiedyedguy** [comment]
Your alternative is probably the best idea there.  That way you can always see it / pivot off of it.

**Comment by GoldenGnu** [comment]
I'm going to implement this the same way the assets added column works (then I can just reuse the code, saving a lot of time).

Another solution will be needed for #265. Journal and transaction are static and never change, Market orders are not static, they change when edited and when someone buy from or sells to the order.

**Comment by GoldenGnu** [comment]
Released in 7.0.0
