### ISSUE TITLE
Wrong Ship Value and Price in Tree view

### ISSUE THREAD

**Issue by Head** [GoldenGnu/jeveassets#271]
Version 6.9.4
In the Tree view inside a Ship Hangar I see under Value the Modules and Cargo and as "Price" a number I cannot identify.
When I right click and say "Edit Price" I get the right price.

See this image for my Astero.
Correct would be: Total 131m, Price 99m
For me it's: Total 32m, **??Price 260k??** and "Edit Price" the correct 99m for the Astero hull.

![image](https://user-images.githubusercontent.com/51700/137318886-30673f89-a323-45a0-b61a-3e83dc674697.png)

The calculation when I right click the column is also correct:
![image](https://user-images.githubusercontent.com/51700/137318206-a35b4938-d2f9-4ef2-b678-7ea64a08b423.png)

**Comment by GoldenGnu** [comment]
Released in 6.9.6

**Comment by Head** [comment]
Really cool! Thank you!
