### ISSUE TITLE
2 suggestions. Transactions and Stockpile.  

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#28]
1. In Transactions when you mark several items and right click on the selected groups it shows the total amount in isk and it also shows the average isk for the selected items. I would like to suggest that the number of items is also shown.

Right now, to see how many items there are in total one have to divide the total amount in isk with the average isk amount.

2. In stockpile, if possible, the ability to see the amount of fuel in fuel bay.

Thank you for the awesome app, and sorry if these suggestions have been brought up before.

**Comment by GoldenGnu** [comment]
1) This is already done for the next feature release (Extra Info: I have been going trough all feature request in the last week to find out what to do next and this one was super easy to do, so, decided to do it right away)

2) It should already be possible to see fuel in POS now? The fuel should be included in the corporation assets for the owner corporation. if that is not the case, I will have to look into it more. I do not own any structures or POS, so, I will need your help to figure out what is required. As I will may need confidential information, I'm going to ask you to email me instead: nkr@niklaskr.dk

**Comment by Amme11** [comment]
i would suggest, if possible, to add the fuel bay of a structure in a system to the "container" category when creating a "New stockpile" list.

**Comment by GoldenGnu** [comment]
Thank you for you feedback.

`Container` are assets containing other assets (Ex: Station Containers and Ships).
`Flag` are non-assets containing assets (Ex: Hangars and Cargo Bays)
So, I think you should use the `Flag` filter for this.

The easiest way to figure out what you need to set the filter to, is find the fuel in the Assets tool and check the value of the `Flag`, `Container`, and `Location`columns

Let me know if this solves your problem :)

**Comment by GoldenGnu** [comment]
A little more info:
You may need to add a ‘Owner’ filter too, if the ‘Flag’ is something used by Characters too

**Comment by Amme11** [comment]
It should show me the fuel in "structurefuel" but it doesn't for some reason, i have added the corp as owner
![1111111](https://user-images.githubusercontent.com/34539717/34072154-5c636bd6-e282-11e7-9972-3561d966abce.jpg)

**Comment by GoldenGnu** [comment]
Can you screenshot the fuel in the assets tool? Be, sure to include the the columns I mentioned above. If you don’t want to share it publicly, you can email me instead.

**Comment by Amme11** [comment]
Hi again, i found the problem.
I was selecting station, flag, container, owner. I switched station to
system and the correct info is showing now.
Thanks again for a great app.

2017-12-16 19:43 GMT+01:00 GoldenGnu <notifications@github.com>:

**Comment by GoldenGnu** [comment]
From the screenshot, I can see the fuel is indeed located in a system (and not a station), so, I will consider this issue resolved.
Getting the Stockpile filters right can be complicated, so good job figuring it out yourself.
I will keep this issue open until I have released the first feature suggestion.
Thank you very much for your feedback :)

**Comment by GoldenGnu** [comment]
Completed in 5.3.0

**Comment by Amme11** [comment]
Thank you :))


2017-12-30 21:28 GMT+01:00 GoldenGnu <notifications@github.com>:
