### ISSUE TITLE
Feature Request: Add "job cost" column to Industry Jobs

### ISSUE THREAD

**Issue by packetizeme** [GoldenGnu/jeveassets#284]
It looks like this is already being pulled from ESI but is not exposed - it would be helpful for tracking costs (without the need to look up by type & date in the journal).

**Comment by GoldenGnu** [comment]
I'm not really sure why that isn't exposed.
It looks like all that is needed is to add the column to the table, so super easy and fast to do

**Comment by GoldenGnu** [comment]
Released in 7.0.0
