### ISSUE TITLE
Log4j / Log4Shell v1.x / v2.x vulnerabilities

### ISSUE THREAD

**Issue by dhenrygithub** [GoldenGnu/jeveassets#292]
Since jEveAssets uses log4j 1.x, I realize the current Log4Shell vulnerability doesn't affect it. However, log4j 1.x is EOL and not receiving security patches, so it would be prudent to move to the current 2.x revs.

==Mitigation==
Is there a mitigation option to disable the log4j code paths in jeveassets?

==Upgrade to Log4J 2.X==
Please.

**Comment by GoldenGnu** [comment]
jEveAssets does not use log4j at all (not 1.X or 2.X), it uses slf4j with logback.
Some of jEveAssets's dependencies may use log4j, however, log4j is replaced by log4j-over-slf4j in jEveAssets. so, it should be safe.
See: http://slf4j.org/log4shell.html for details.
