### ISSUE TITLE
Feature request: Add "Output Name" to available columns on Industry Jobs tab

### ISSUE THREAD

**Issue by LakMoore** [GoldenGnu/jeveassets#294]
Would it be possible (easy even?) to add the name of the output item on the industry jobs tab?  We have the output count (which is very useful) but the item name can sometimes differ slightly to the BP name.
![image](https://user-images.githubusercontent.com/6624290/147937452-6abb1434-0254-4303-b337-e84490dbb620.png)

**Comment by GoldenGnu** [comment]
Released in 7.1.0
