### ISSUE TITLE
Export profiles

### ISSUE THREAD

**Issue by xbartx99** [GoldenGnu/jeveassets#295]
I got a new machine and would like to move all my data to a new machine.
Syncing across network would be amazing but just saving to a file to import on another PC would be great.
Being about top backup to cloud(like saving to google drive would be nice)

**Comment by GoldenGnu** [comment]
All you need to do is move the entire jEveAssets settings directory `.jeveassets` (see: [Settings location](https://jeveassets.nikr.net/faq#settings_location)) to your new computer.

I made a small article about how to keep data in the cloud: [jEveAssets cloud settings](https://jeveassets.nikr.net/cloud).
Please, let me know if have any ideas to improve it or need additional help to get it working.

There is already an issue for cloud support in jEveAssets: https://github.com/GoldenGnu/jeveassets/issues/5

I do not offer support via GitHub, if you want support for jEveAssets, you will need to join the [jEveAssets Discord server](https://discord.gg/8kYZvbM).
