### ISSUE TITLE
Make a Add button in the Reprocessed tool

### ISSUE THREAD

**Issue by GoldenGnu** [GoldenGnu/jeveassets#297]
Allow users to add item types to the reprocessed tool from within the tool:
JButton("Add") > JAutoCompleteDialog (with all items that can be reprocessed)

**Comment by Simonsen01** [comment]
I can take a look on this but just a quick clarification.
The item selection limited to what the user already has in their assets or is it any item within the game?

**Comment by GoldenGnu** [comment]
No, you can select any item. It's not connected to your assets.

The way I envisioned this feature, is using a `net.nikr.eve.jeveasset.gui.shared.components.JAutoCompleteDialog<Item>` with `StaticData.get().getItems().values()` as data (Note: you will need to filter out the items with no reprocessing data). And showing it via an "Add" button (next to the "Remove All" button) on the toolbar.
However, I'm open to discussing it, if you want to implementing it another way.

I'm available for questions on the jEveAssets Discord: https://discord.gg/8kYZvbM I will happily help you with any question you may have about the code.

Please, also read the code guide: https://github.com/GoldenGnu/jeveassets/wiki/Source (It's very short).

Since this is a new feature, you need to make the PR to the [feature-branch](https://github.com/GoldenGnu/jeveassets/tree/feature-branch).

I have assigned the issue to you, thank you for offering to contribute to jEveAssets 👍

**Comment by GoldenGnu** [comment]
Released in 7.1.0
