### ISSUE TITLE
Suggestion: Have structure updates run in the background

### ISSUE THREAD

**Issue by hedge00** [GoldenGnu/jeveassets#30]
Since structure updates take anywhere from 20 minutes to several hours to complete, and modal dialog prevents interaction with the software until it's done, it would be better to have structure updates run in the background. And please include the estimated time of completion somewhere once the update is underway.

**Comment by GoldenGnu** [comment]
I think that is a reasonable request.
Thank you for your suggestion. :)

**Comment by GoldenGnu** [comment]
Released in 5.3.0
