### ISSUE TITLE
Hide stockpile from context menu

### ISSUE THREAD

**Issue by RustRaven** [GoldenGnu/jeveassets#300]
It would be very handy to be able to hide a stockpile from the context menu accessed when left clicking the Stockpile button, rather than having to open the Show/Hide menu and navigate the list until you find the stockpile(s) you want to hide:
![image](https://user-images.githubusercontent.com/36562351/151670261-20452247-ad52-4b72-b83f-c47be1f08f4b.png)

**Comment by GoldenGnu** [comment]
Released in 7.1.0
