### ISSUE TITLE
weird UI bug when editing a Stockpile

### ISSUE THREAD

**Issue by Sdeeel** [GoldenGnu/jeveassets#303]
![X4K9vSe](https://user-images.githubusercontent.com/25287916/152329136-6f3b97a5-4291-449f-91f1-564cd313ac77.png)

Not sure why it happends but when i try to edit a stockpile that happens
Hope you can help with that.

**Comment by GoldenGnu** [comment]
I have a few question:
What operation system are you on?
What version of Java do you have and is the 64 or 32bit version?
Are you display a 4K one?
How much RAM is jEveAssets using?

**Comment by Sdeeel** [comment]
> I have a few question: What operation system are you on? What version of Java do you have and is the 64 or 32bit version? Are you display a 4K one? How much RAM is jEveAssets using?

i Currently use Windows 11 and Java 8.0.3210.7 64bit
i use a 3440x1440 display and right now it's using ~1,2gb of ram

**Comment by GoldenGnu** [comment]
Do you have multiple displays?
Are they HDR enabled?

**Comment by Sdeeel** [comment]
i use a normal 1440p and the 3440x1440p display, none of them had HDR enabled

**Comment by GoldenGnu** [comment]
Okay, try the following workaround:
https://github.com/GoldenGnu/jeveassets/issues/11
Also, please, to changing the theme:
Options > Options... > Colors > Look and Feel (They each of them, do note that you need to restart for the look and feel change to take effect)

**Comment by Sdeeel** [comment]
seems like that fixed it.
using the dark mode now and it's working fine
added and edited about 30 stockpiles and no issues so far, thanks :)

**Comment by GoldenGnu** [comment]
Okay, I'm going to close this issue, as the workaround resolved it.
Leave a comment to get the issue reopened.
