### ISSUE TITLE
Idea  Externe SQL Server

### ISSUE THREAD

**Issue by SpartaWarsec** [GoldenGnu/jeveassets#305]
would it be possible to integrate an external server where a SQL is running to save my data sets there?

**Comment by GoldenGnu** [comment]
Not directly, but, you can export to sql and import it in a database. From the next release 7.1.0, you will be able to export from the command line, opening it up to be an automated process. See #270 for detailed. Would that fit your needs?

jEveAssets store almost all It’s data in xml, so, there isn’t a backend database (a tiny portion of the data is stored in an SQLite, though, and some of the data is stored in json too).
The main reason for that is accessible and backwards completely. jEveAssets are able to load files from any previous version of jEveAssets.

**Comment by SpartaWarsec** [comment]
I'll read through the post #270


but it would be nice if the following were possible

An options window for SQL server login (SSL NON-SSL) and ip 
so that all the data is written in there.

If you then simply delete the tables before each export to the sql, it would be enough if the table is then created again every time ... it doesn't have to be compared, etc

And a button that forces manual writing into the table
you could do that with the update button together


It would be best if Jeveasset then also obtains the data from there
but first would be NICE

**Comment by GoldenGnu** [comment]
You will have to do your own importing. That shouldn’t be very hard to write a script to do that. 
There are options to both delete and create the table, that is also included in the CLI.
What you’re requesting is a huge feature that wouldn’t be used by very many people. So, I’m going to decline it.
You’re always welcome to contribute the changes yourself, though. As long as the code is up to standard I will happily accept it.
