### ISSUE TITLE
Try to resolve mismatches when fixing expired tokens

### ISSUE THREAD

**Issue by E-351** [GoldenGnu/jeveassets#306]
When token expires jeveassets requires to click on specific character and then sign in as that character again. This can be bit problematic as people with a lot of accounts might not know what character is where just by it's name. Possible solutions:

1) Before rejecting keys due to mismatch try if the key would match any other character stored in jeveassets and if so either just use the new ones or ask user whether he wants to use it (talking about the screen below)
![image](https://user-images.githubusercontent.com/46429852/156738306-8a81ec63-284c-4fc2-b0f2-6b729859b86d.png)

2) Alternatively remove the "Edit" button specific to each character and just use "Add" and automatically match against existing characters as I can't think of any reason why I'd want the same characterID+characterOwnerHash multiple times.

**Comment by GoldenGnu** [comment]
The way I’m leaning now, is to make Add auto match characters and have edit require a match. I’m not sure that is the best solution, but, that is what makes most sense to me.

**Comment by E-351** [comment]
Yeah, I do believe it is the best solution, there should really not be any need ever to have a duplicate characterid+hash - it's how I use it in my apps as well.

**Comment by GoldenGnu** [comment]
Released in 7.2.0
