### ISSUE TITLE
No character selection when only one character is setup for Market Details Open

### ISSUE THREAD

**Issue by zinsmeik** [GoldenGnu/jeveassets#307]
Hi,

if you use "Stockpile" and the column "Market details" and click on the "Open" then jEveAssest display a dialog to select the in game Character.
If you have setup only one character this dialog is not needed. Instead jEveAsset should use the eve character which is there.

In advanced, if you have more then one character setup it would be nice to define a default lookup character without the character selection dialog and maybe display the character selection dialog when you Shift Click "Open"

Greetings

Klaus

**Comment by GoldenGnu** [comment]
I think it makes sense to move the character selection to the toolbar.

**Comment by GoldenGnu** [comment]
Released in 7.3.0
