### ISSUE TITLE
jEveAssets window moves to front on mouseover (xmouse)

### ISSUE THREAD

**Issue by hedge00** [GoldenGnu/jeveassets#31]
I'm not sure whether this may be a Java issue, but when the jEveAssets window is partially covered by another window, and I move my mouse over the visible portion of the jEveAssets window, the entire jEveAssets window will spontaneously jump to the front, on top of everything else. It may be relevant that I have xmouse enabled via winaero tweaker and set to "focus follows mouse". Other windows behave properly on mouseover, gaining focus but maintaining their layer in the stack until clicked.

**Comment by GoldenGnu** [comment]
Looks like that behavior is not supported by Java.  :(

I think I can hack something together, that works the same way, though.
I will have tool look into it more, though.
If it's possible, It will be something you have to enable in the jEveAssets options.

**Comment by hedge00** [comment]
If it's a Java limitation then don't worry about it. I can simply minimize the window when I don't want to interact with it. Thanks for checking! 🥇

**Comment by GoldenGnu** [comment]
Okay, closing the issue then.
As always, thank you for your feedback :)
