### ISSUE TITLE
Export to sql - wrong working -createtable and droptable parameters

### ISSUE THREAD

**Issue by rr2070** [GoldenGnu/jeveassets#310]
I am using export to sql and find out, than in my opinion, something is wrong with -droptable and -createtable parameters. When I use something like that: java -jar d:\eve\jeveassets-7.0.0\jEveAssets\jeveassets.jar -e -f d:\eve\sql -sql -droptable  -nodate in every file I have create table definition. When I use something like that: java -jar d:\eve\jeveassets-7.0.0\jEveAssets\jeveassets.jar -e -f d:\eve\sql -sql -createtable -nodate I have
 -- jEveAssets Sql Export
-- version 7.1.1
-- https://eve.nikr.net/jeveasset
DROP TABLE IF EXISTS ;
INSERT INTO  (NAME, NAME_TYPE, NAME_CUSTOM, TAGS, GROUP, CATEGORY, OWNER, LOCATION, SECURITY, SYSTEM, CONSTELLATION, REGION, FACTION_WARFARE_SYSTEM_OWNER, CONTAINER, FLAG, PRICE, PRICE_SELL_MIN, PRICE_BUY_MAX, PRICE_CONTRACT, PRICE_REPROCESSED, TRANSACTION_PRICE_LATEST, TRANSACTION_PRICE_AVERAGE, TRANSACTION_PRICE_MAXIMUM, TRANSACTION_PRICE_MINIMUM, PRICE_BASE, VALUE_REPROCESSED, VALUE, PRICE_REPROCESSED_DIFFERENCE, PRICE_REPROCESSED_PERCENT, COUNT, COUNT_TYPE, META, TECH, VOLUME, VOLUME_TOTAL, VALUE_PER_VOLUME, SINGLETON, ADDED, MATERIAL_EFFICIENCY, TIME_EFFICIENCY, RUNS, CITADEL, ITEM_ID, LOCATION_ID, TYPE_ID) VALUES............

**Comment by GoldenGnu** [comment]
So, this is multiple issues:
1) `-droptable` `-createtable` `-extended` are always true
2) tableName default to an empty string (resulting in ```DROP TABLE IF EXISTS `` ``` )
2) When the tableName is set via the GUI, it's not used when exporting from the CLI.

**Comment by GoldenGnu** [comment]
Released in 7.2.0
