### ISSUE TITLE
Auto update information

### ISSUE THREAD

**Issue by xbartx99** [GoldenGnu/jeveassets#311]
Would it be possible to add a feature to schedule when it update all character information?
I would like to use it to monitor sell order and assets so I can plan accordingly.

**Comment by Dusty-Meg** [comment]
See https://jeveassets.nikr.net/cli
Namely the -update flag

**Comment by GoldenGnu** [comment]
I’m going to close this as resolved.
Please comment on the issue if you want it re-opened.
