### ISSUE TITLE
Screen corruption (Nahimic Overlay)

### ISSUE THREAD

**Issue by john2288** [GoldenGnu/jeveassets#313]
I am using the newest jeveassets. when using the stockpiles tab i am ocassionally getting a strange issue where the screen is copying itself in random locations on my screen, causing me to have to reload.
It seems to happen when using right click or the stockpile menu, as it occurs randomly i'm not sure how to reliably reproduce the issue.
Running windows 11.
[Example image](https://pasteboard.co/JZLPvYwuYIA7.png)

**Comment by GoldenGnu** [comment]
Thank you for your bug report.
In case you didn't already update java to the latest version, please try that (Java 8 Update 331, released 19. April).
Let me known if that resolves the problem.

**Comment by Fyrestrom** [comment]
I have the same issue as OP. It is not only the stockpile that triggers it. If I move the window to another screen it fixes itself for a few moments but as soon as I hover over anything it starts again.

**Comment by GoldenGnu** [comment]
Please email me the log:
https://wiki.jeveassets.org/faq#email_log

**Comment by GoldenGnu** [comment]
I have just released version 7.2.0. It manages the swing paint thread a little better, there is a chance it will resolve this issue.
Please let me know if you're still able to reproduce with the latest version of jEveAssets and java.

**Comment by Fyrestrom** [comment]
I just tested it, and I am able to reproduce the problem. Everything seems fine until I try to edit an item in a stockpile.
![image](https://user-images.githubusercontent.com/10393372/170827795-74a16cf1-299d-427f-ae49-dbdb91e1e255.png)
And then the whole app starts fracturing.
![image](https://user-images.githubusercontent.com/10393372/170827823-0b0ee2f6-1bca-4b28-ad6f-62833e342fa4.png)

**Comment by GoldenGnu** [comment]
Could you please email me the log: https://wiki.jeveassets.org/faq#email_log

**Comment by Fyrestrom** [comment]
Sorry, I missed your original request for the logs. I sent them now.

**Comment by GoldenGnu** [comment]
@john2288 
Please try the following:

Uninstall all versions of java: https://www.java.com/en/download/help/uninstall_java.html

Then download and install the latest version of java:
https://www.java.com/en/download/manual.jsp (Windows Offline (64-bit))

Let me know if that resolve the issue for you or not.

**Comment by GoldenGnu** [comment]
Resolved by updating to the latest version of Java.

**Comment by GoldenGnu** [comment]
Released in 7.3.0
