### ISSUE TITLE
Jeveassets steals focus during ESI data update

### ISSUE THREAD

**Issue by wiblaa** [GoldenGnu/jeveassets#319]
Jeveassets steals focus 1-2 seconds after initiating an ESI update, as the "Updating" window opens.
![image](https://user-images.githubusercontent.com/24319659/167302537-5e337254-73b7-45e6-a547-06afa54e9167.png)
When that happens, I have often already switched to a different window and started typing, and as the "cancel" button is pre-selected, hitting space or enter will cancel the update, forcing a 1 hour wait to hit the assets ESI endpoint again.

**Comment by GoldenGnu** [comment]
Released in 7.2.0
