### ISSUE TITLE
Values

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#32]
In values having the ability to exclude items.

For example: 
Best Asset:
Men's 'Wirepoise' Facial Augmentation 
10 000 000 000,00 isk

This item, as the price data is grabbed from CREST, adds 10b to my total value. Items like this makes the assessment of ones worth less curate. 

If possible, adding another filter in Asset statusbar that removes item from Values tab calculation.
--

**Comment by GoldenGnu** [comment]
Prices are estimates, it will always be like that. Prices are a range of values, condensing them down to a single value will always be imperfect.

If you feel like a particular item have the wrong price, you can set the price manually:
1) Find the item in the Assets tool
2) Right click the item
3) In the popup menu select: Price > Edit
4) Enter the correct price
5) Press OK
6) The new price will now be used for that item type everywhere in jEveAssets (including the Values tool).

Another option is to change the price data options:
1) Options > Options... > Price Data
You can test different options to see what works best for you.
Note: Changing some of the options require updating the price data, before they take effect.

I hope the above solutions solves your problems, if not, please, let me know why the above solutions does not fit your needs and I will see what I can do.

Thank you for your feedback :)

**Comment by GoldenGnu** [comment]
I assume the suggested solutions worked for you (as you never replied).
So, I'm going to close this issue as resolved :)

**Comment by Amme11** [comment]
I have have the time to test your solution and it worked, once again, thank
you.

2018-01-14 11:12 GMT+01:00 GoldenGnu <notifications@github.com>:
