### ISSUE TITLE
Stockpile Groups

### ISSUE THREAD

**Issue by wiblaa** [GoldenGnu/jeveassets#321]
Feature request - adding more organizational tools to the stockpile window

Possible ways to do this: 

groups (individual stockpiles can be added to a group that can be collapsed) 
labels (enables filters (already implemented) and other ways to dynamically sort and organize stockpiles, might be preferred over groups?)

**Comment by GoldenGnu** [comment]
Related: #207

**Comment by GoldenGnu** [comment]
I’m currently leaning towards stockpile tags. As It would make it possible to visually mark the stockpile and hide/show stockpile with filters. The filter system offer a lot flexibility out of the box.

**Comment by ImperialStarkDestroyer** [comment]
"groups (individual stockpiles can be added to a group that can be collapsed)"

You can do this by creating a new stockpile with the initial stockpiles as subpiles. 
For e.g. I have 4 x stockpiles that are different types of Missiles on the market, then I have one Master one that subpiles all those so I can see the total missiles.

Not sure if that helps or not!

**Comment by GoldenGnu** [comment]
Released in 7.6.0
