### ISSUE TITLE
Configure colors for indu activities

### ISSUE THREAD

**Issue by thegilm** [GoldenGnu/jeveassets#324]
As a heavy indu user I'd like to set different colors for different industrial activities under the "Industry Jobs" tab, so I can get a clear visual distinction of them.

**Comment by GoldenGnu** [comment]
I really like that idea!
What colors would you choose for each activity?

**Comment by thegilm** [comment]
Hmm, for the start maybe we could stick with the ingame colors so, basically orange for the manufacturing (e98c02), blue for science jobs (2f68a6) and light greenish blue (11d1b7) for reactions?
Although it'd be nice to have an option to configure ME research different from TE research and copying different from invention for example. I attached a sample screenshot with different activities for one char.
![exefile_z5bky4HY6A](https://user-images.githubusercontent.com/652419/168770670-c3897a56-d1cd-4dcc-aae2-f3fd47f024a3.png)
![javaw_YBnI3oGmpa](https://user-images.githubusercontent.com/652419/168771352-5c7b4f1f-8cc7-495f-ae24-303ef2f134b0.png)

**Comment by GoldenGnu** [comment]
Thanks. I think using the in-game colors is the right way to go, I'm going to use the jEveAssets color scheme, though.
It's super easy to add colors to tables in jEveAssets, so, I pretty much already finished it.
The feature will be in the next feature release.
![colors](https://user-images.githubusercontent.com/11528122/168792029-5018695a-d394-44fd-8cbf-92d3b76b1602.png)

**Comment by GoldenGnu** [comment]
Released in 7.2.0
