### ISSUE TITLE
jEveAssets: Stockpiles: Blueprint Copy Runs shows 0 incorrectly

### ISSUE THREAD

**Issue by OlivierPelletier** [GoldenGnu/jeveassets#326]
Stockpile doesn't show the correct number of runs for BPC.

I tried cloning, remaking the stockpile and choossing "universe" for the location and it still shows 0.
Blueprints are located in a Corporation hangar.

Version: jEveAssets 7.2.0

**Comment by GoldenGnu** [comment]
Yes, I already fix the bug. But, I don’t know when I will have time to release a new version.

**Comment by GoldenGnu** [comment]
Released in 7.2.1
