### ISSUE TITLE
Orders in unknown locations

### ISSUE THREAD

**Issue by rpoplawski0** [GoldenGnu/jeveassets#327]
Hi,
Since the recent update, I'm getting the following error every time I start jeveassets and run first "Update All"

<img width="200" alt="2022-06-01 11_19_52-Orders in unknown locations" src="https://user-images.githubusercontent.com/19431274/171383188-e3856780-cd9b-4447-b13d-27416e1f4677.png">
Updating the structures info resolves the problem until I close and open jeveassets again.

My locations.xml file is from 2022.02.16 but I'm not sure if this is related.

**Comment by GoldenGnu** [comment]
The dialog is meant to be shown only once per run. I’m sure why you keep getting the error. It’s either because jEveAssets is not able to resolve the structure or because of a bug. I will look into today…

**Comment by GoldenGnu** [comment]
Fix released in 7.3.0
