### ISSUE TITLE
Add Janice as a Market Prices source

### ISSUE THREAD

**Issue by jtrenaud1s** [GoldenGnu/jeveassets#328]
Janice provides an api to obtain immediate prices, featuring an option to include prices from both jita and perimeter TTT. This would be great for people who use TTT for buy orders and jita for sell orders.

I propose an option be added to the Market Prices settings to allow use of Janice's api to obtain prices. Janice requires api keys, obtained upon request to use the api, so the api key could be entered by the end-user if they own one to avoid using a dedicated api key and hitting the rate limit.

https://janice.e-351.com/api/rest/docs/index.html

**Comment by GoldenGnu** [comment]
Released in 7.3.0
