### ISSUE TITLE
Changing settings for colors/look &feel takes long to update

### ISSUE THREAD

**Issue by wiblaa** [GoldenGnu/jeveassets#334]
When changing settings for look & feel, jeveassets seem to trigger a full update of all data, which takes several minutes for me, on two different computers.

[19:52] GoldenGnu: I could 100% just repaint the tables, though.

**Comment by GoldenGnu** [comment]
- [ ] General
- Tools
   - [ ] Show
   - [ ] Assets
   - [ ] Overview
   - [ ] Stockpile
   - [ ] Market Orders
   - [ ] Transactions
   - [ ] Journal
   - [ ] Contracts
   - [ ] Tracker
- Values
   - [ ] Prices
   - [ ] Names
   - [ ] Locations
   - [ ] Tags
- [ ] Colors
- [ ] Market Prices
- [ ] Contracts Appraisal
- [ ] Reprocessing
- [ ] Proxy
- [ ] Window

**Comment by GoldenGnu** [comment]
Released in 7.3.0
