### ISSUE TITLE
Show Reprocesses value from a clip board paste

### ISSUE THREAD

**Issue by VartSark** [GoldenGnu/jeveassets#335]
Hi, I do a fair few missions and combat sites and tend to reprocess everything to minerals to either sell to corp or sell on market. In the reprocess tab of the application I thought that I could import the items (and quantity of those items) that are on my clipboard and the application would show me, based on my skills and a market (mainly a trade hub) if it would be more profitable to sell (either at sell or buyers price) or to reprocess.

Having a tool like this that shows me enmass that i could filter to show items to reprocess or items to sell would be greatly beneficial in optimizing the loot I get from these sites rather than manually check each item or just reprocessing everything as a matter of default

GoldenGnu advised that this was not possible in the app at the moment but to submit the idea here on github, so here it is

Regards, V

**Comment by VartSark** [comment]
an example of the clipboard data is as follows

from item view
Inferno Rage Rocket	850
Caldari Navy Inferno Rocket	600
Caldari Navy Mjolnir Rocket	328
Caldari Navy Nova Rocket	210

or from list view
Caldari Navy Inferno Rocket	600	Rocket			3 m3	353,898.00 ISK
Caldari Navy Mjolnir Rocket	328	Rocket			1.64 m3	207,646.96 ISK
Caldari Navy Nova Rocket	210	Rocket			1.05 m3	131,113.50 ISK
Inferno Rage Rocket	850	Advanced Rocket			4.25 m3	68,671.50 ISK

**Comment by GoldenGnu** [comment]
This feature would need to handle count of reprocessed item, see:  #302

**Comment by GoldenGnu** [comment]
Released in 7.4.0
