### ISSUE TITLE
Missing Blaze skins in the database

### ISSUE THREAD

**Issue by Djoraan** [GoldenGnu/jeveassets#34]
There are some items missing in the db. The 5 limited "Blaze" Squadron skins don't show as such in the app, instead they show up as: Name: !47101 - !47106

==> https://community.eveonline.com/news/dev-blogs/a-new-skin-and-a-tribute-to-a-fallen-wingman/

**Comment by GoldenGnu** [comment]
Thank you for letting me know, you're not the first to notice, but, I appreciate that you reported it! :)
Unfortunately it's out of my hands, as they're not included in the latest SDE.
The last SDE was released 2017-12-05 and the skins was released 2017-12-12.

I'm going to close this issue. If the skins are still missing after then next jEveAssets data release, please, create a new issue.
Thank you for your feedback

**Comment by GoldenGnu** [comment]
New static data have been released for jEveAssets, please, let me know if this fix the issue :)

**Comment by Djoraan** [comment]
Sry i missed the comment, yes its fixed
