### ISSUE TITLE
Text field of "custom" refining equipment in options

### ISSUE THREAD

**Issue by eerozeteen** [GoldenGnu/jeveassets#340]
Text field of "custom" refining equipment in options looks like be "int" and we can.t add float number to it (like 61,72% for base "t2 rigged tatara" in null space).
Field should let us put float number to it.
![image](https://user-images.githubusercontent.com/4992183/189222528-2d7c3f5e-f4f1-4b0d-bf0d-ed8733bfde99.png)

**Comment by GoldenGnu** [comment]
Released in 7.3.0
