### ISSUE TITLE
Feature Request: Stockpiles to show 'total' amount of stuff to make

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#341]
Would it be possible to get Stockpiles to show the 'total amount of stockpiles you have' for each stockpile?

For example, if I set up a stockpile with # 1 that is just the recipe for Fuel Blocks, it would be handy to show something that is essentially 'You can make # numbers of these in total with the current assets/criteria'

See attached screenshot for example
![image](https://user-images.githubusercontent.com/111640520/189882548-096937ab-7916-43a3-9707-6791a61f4dd3.png)

**Comment by ImperialStarkDestroyer** [comment]
Could also be a column I guess too if that's easier, showing how many stockpiles worth of that ingredient you have. So in the example above Robotics would say '89', Hydrogen Isotopes '74.01' so you can just look down the column and see the lowest amount to see how many you can make

**Comment by GoldenGnu** [comment]
Available via Stockpile.getPercentFull()

**Comment by ImperialStarkDestroyer** [comment]
Works great, thanks! Fixed

**Comment by GoldenGnu** [comment]
Released in 7.3.0
