### ISSUE TITLE
Stockpile page can get corrupted if laptop goes idle

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#343]
![jeveassets stockpile sleep](https://user-images.githubusercontent.com/111640520/192143771-288e50a0-0155-439c-8ecc-c5b015acb988.png)
![jeveassets stockpile sleep 2](https://user-images.githubusercontent.com/111640520/192143774-286108fa-558d-4a2d-83c5-2df5b8a1d7b2.png)

1. Load jEVEAssets with a laptop
2. Select Stockpiles, making sure you have some set up
3. Close the lid of the laptop and have some lunch
4. Come back later and sign in to the laptop
5. The stockpile page will be get messy - see attachments

It's fine after closing and reopening the program

**Comment by GoldenGnu** [comment]
This is often caused by overlays like Nahimic, Nvidia, or similar. If you have either installed disabling the overlay usually resolve the problem. Sadly it's almost impossible to resolve issues like this without being able to reproduce them and I have never had any issues myself.
