### ISSUE TITLE
Can't paste in values with a thousand separator to the Target column

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#344]
More of a mild annoyance than anything serious. 
I use it a lot to shopping list a list of components and then paste the values back in for the equivalent blueprint runs stockpile

Steps;

1. Set up a stockpile with a few items
2. Double click in the target field and paste in a value with a thousand separator, e.g. 1,000
3. Press enter, it goes red and doesn't save

**Comment by GoldenGnu** [comment]
Released in 7.4.0
