### ISSUE TITLE
Feature request: Ability to search/filter skills of characters

### ISSUE THREAD

**Issue by douglas24** [GoldenGnu/jeveassets#345]
Ability to search/filter skills of characters similar to how we can search/filter other assets.

For example it could have each skill's completed level as a separate 'item', so one filter using Skill Name contains Cybernetics and Level Complete contains 3 and see which characters have Cybernetics Level 3 fully trained.

The only skill ESI usage at the moment is full extraction valuation.

**Comment by GoldenGnu** [comment]
Released in 7.6.0
