### ISSUE TITLE
Authorize Button not Blue/selectable 

### ISSUE THREAD

**Issue by poundjd** [GoldenGnu/jeveassets#346]
When I try to authorize a character on the authorization screen the "Authorize Button" is not Blue/selectable.

**Comment by GoldenGnu** [comment]
You have to click the image/portrait of the character you want to add, then the button will become clickable. Also, you need JavaScript enabled in your browser for the site to work correctly. Do note that the site is a CCP site and outside my control, so the bug report should technically go to CCP

**Comment by poundjd** [comment]
I have clicked the picture, singularly and multiple times.

**Comment by GoldenGnu** [comment]
As, I said, this is not the right place to get help with your problem. You should make a support ticket on the Eve Online support page.
