### ISSUE TITLE
Market Slot Count Free/Used - Industry Tab - Feature

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#347]
I found myself creating a work around to track market slots across many alts after I found that the Industry tab did not contain used/free market slot count.  I created a spreadsheet that required me to export my character skills from evemon to track the skills to get the total market slot count.  I then used jeveassets to copy and paste from the market order tab the active info into the spreadsheet keeping the name, corp and location data.  With this I was able to extrapolate that based on x skills and used slots I have X free slots.  Even a summary of where they were all located. See this for the example [Spreadsheet Sample Link](https://i.imgur.com/zGOnC34.png).  

It would be useful to see free/used market slots in the industry tab as a feature.  Thank you. Edit: Also this could be useful for contracts, corp contracts for seeders who list bulk stuff for alliances, corps and public.

**Comment by Mr00Anderson** [comment]
Base Market Slots = 5

For each level trained:
Trade = 4
Retail = 8
Wholesale = 16
Tycoon = 32

**Comment by GoldenGnu** [comment]
Released in 7.4.0
