### ISSUE TITLE
Transactions - Add volume as a column

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#350]
Would it be possible to get volume added as a column to the transactions page?

Reason for this is that it costs me ISK/m3 to import to null, so if this was available I could set up a formula column to calculate the 'real' profit. 

Or, just a box at the top we could put an ISK/m3 value in for it to be included with the existing column profits.

**Comment by GoldenGnu** [comment]
Released in 7.4.0
