### ISSUE TITLE
Feature Request: Ability to sort stockpiles even when they include subpiles

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#352]
https://discord.com/channels/565306310229229569/565306310229229571/1043162217702510682

It would be handy to be able to fully sort the stockpiles by a column, even if they include subpiles. 
This helps to see what is running out first when deciding what order to build things :) Thanks!

As per the below screenshot:

![image](https://user-images.githubusercontent.com/111640520/202721146-4dde4c02-9cf2-4825-9d45-18b630d3593e.png)

**Comment by GoldenGnu** [comment]
Released in 7.6.0
