### ISSUE TITLE
Feature Request: Changes to Tracker tab graph date, time and abbreviated day naming

### ISSUE THREAD

**Issue by solarseven** [GoldenGnu/jeveassets#356]
I feel it is a bit noisey to have repetitive date text at the bottom of the Tracker tab graph. 
Only showing the year, month and day whenever they change would help to cut down on date text that does not really serve any meaningful purpose. 
Have the day number only shown once per day and other data points within that day be military time stamps as used in EVE Online.
Along it a day number change using abbreviated day names (su, mo, tu, we, th, fr, sa) would assist to more quickly understand tracker history data.

**Comment by GoldenGnu** [comment]
Released in 7.6.0
