### ISSUE TITLE
Stockpiles - Input blueprints to a new stockpile and being able to select manufacturing materials

### ISSUE THREAD

**Issue by ImperialStarkDestroyer** [GoldenGnu/jeveassets#357]
What I'd like to do is via the import/new stockpile option, use a list such as:

Capital Semiconductor Memory Cell II Blueprint	4
Capital Thermal Armor Reinforcer II Blueprint	2
Capital Trimark Armor Pump II Blueprint	2
'Crossbow' Focused Medium Beam Laser I Blueprint	3

And then be able to set 'manufacturing materials', with it taking the number above as the number of runs, and adding all the manufacturing materials needed to the new stockpile. 

Would need to assume they're all the same ME / TE I guess. Might need to pop up the engineering complex prompt too

**Comment by GoldenGnu** [comment]
Also allow selecting BPO/PBC/Runs

**Comment by GoldenGnu** [comment]
Released in 7.6.0
