### ISSUE TITLE
Stockpiles: Hangar Flag matches all flags

### ISSUE THREAD

**Issue by LakMoore** [GoldenGnu/jeveassets#358]
As soon as I add the "Hangar" flag to my filter, the items are included in the stockpile regardless of their flag
![image](https://user-images.githubusercontent.com/6624290/204091929-39a898e3-69db-4cd6-ab07-9961328c9cd0.png)

**Comment by GoldenGnu** [comment]
So, I finally got around to look at the code. It checks if any of the parent assets have the flag too. I think it would be a good improvement to add an option to only match the exact assets. So, this is now a feature request, as apparently this is how it was made to work (long time ago).

**Comment by LakMoore** [comment]
Interesting. I imagine that has its use cases.

My use case is to distinguish between a module in the hanger to be sold or
a module in use, fitted to a ship.

Maybe I’m filtering on the wrong thing.

I think I actually started using “container is ‘None’”

**Comment by GoldenGnu** [comment]
Released in 7.5.0
