### ISSUE TITLE
nikr.net is offline

### ISSUE THREAD

**Issue by TyrHeimdalEVE** [GoldenGnu/jeveassets#359]
@GoldenGnu 

It seems like the domain name `nikr.net` should be using the following nameservers:
```
nikr.net.               3600    IN      NS      ns1.simply.com.
nikr.net.               3600    IN      NS      ns3.simply.com.
nikr.net.               3600    IN      NS      ns4.simply.com.
nikr.net.               3600    IN      NS      ns2.simply.com.
```

Currently, they domain is using:
`ns1.surf-town.dk`
`ns2.surf-town.dk`
... and both of them are down.

Just wanted to give a heads up if you haven't realized yet.

**Comment by GoldenGnu** [comment]
Thanks you. For some reason the DNS record was never moved when transferring to simply, but, still continued to work.
I'm going to take this opportunity to move the nikr.net domain elsewhere. So, things may be offline for a while.
A lot of jEveAssets functionality is bound to the nikr.net domain (auto update, web site, maven repo), those things will not work until I get it all setup correctly again. I'm super sorry for the mess and hope to be able to correct it as soon as possible.

**Comment by TyrHeimdalEVE** [comment]
May I suggest Cloudflare? You get free DNS hosting with them and then your Domain Registrar doesn't really matter much. Also you can transfer the domain there and pay at wholesale cost which is nice. :smile: 

If you're missing the correct IP address for the A-records, it _should_ be `93.191.156.106`. I set it in my Hosts file and can access the site.

The Simply DNS servers does have the DNS Zone;
```
; <<>> DiG 9.18.8 <<>> -t ANY nikr.net @ns1.simply.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15757
;; flags: qr aa rd; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nikr.net.                      IN      ANY

;; ANSWER SECTION:
nikr.net.               3600    IN      A       93.191.156.106
nikr.net.               3600    IN      NS      ns1.simply.com.
nikr.net.               3600    IN      NS      ns2.simply.com.
nikr.net.               3600    IN      NS      ns3.simply.com.
nikr.net.               3600    IN      NS      ns4.simply.com.
nikr.net.               3600    IN      MX      10 mx.simply.com.
nikr.net.               3600    IN      TXT     "v=spf1 include:spf.simply.com ?all"
nikr.net.               14400   IN      SOA     ns1.simply.com. hostmaster.simply.com. 2020120200 14400 3600 1209600 3600

;; Query time: 16 msec
;; SERVER: 91.197.248.78#53(ns1.simply.com) (TCP)
```

Thanks for the swift response!

**Comment by GoldenGnu** [comment]
Everything should be back online now. Feel free to comment here if you find any issues.
