### ISSUE TITLE
Market Orders Tab column addition

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#365]
With the `Market Orders` tab having outbid information; it would be useful to setup a calculation for listing ranges based on jita buy and jita sell.   Currently the issue would be that only one Market price is listed and that is selected in the jeveasset options.

Use cases:
With both prices being list, one could use it to calculate a price spread using custom columns, such as being able to reference sell and buy price and, in a formula, find then in-between price be it split or other to use in calculating.  If the weigh column is added than further calculations can occur such as a compound equation to find a total listing price as a minimum or maximum.  For example
(([Jita Buy]-[Jita Sell])*0.50)+[Jita Buy] to calculate out a split, or (([Jita Buy]-[Jita Sell])*0.75)+[Jita Buy]  (calculating at 75% the difference)

Edit: This would also be useful on the `Stockpile` tab as well.

**Comment by GoldenGnu** [comment]
jEveAssets is never going to get price data for multiple location (this decisions was made to keep the usage of the price APIs at a reasonable level, as jEveAssets hit the APIs for every single user). But, I added sell min and buy max to the market orders tool and will do the same to the stockpile tool.

**Comment by GoldenGnu** [comment]
Released in 7.5.0
