### ISSUE TITLE
Create Stockpiles from Contract/Fitting/Industry job tabs

### ISSUE THREAD

**Issue by jpkoester1** [GoldenGnu/jeveassets#366]
I have been playing around with the Stockpile tab in the last couple of days and noticed one thing that is bothering me a bit and might be improved in that section of the tool. If I create a new stockpile from one of the other jEveAssets windows the new stockpile includes all items but always has "1" as target quantity. 

It would be great if the new stockpile could use the available amounts from the other window as default target quantity. 

As a use-case lets say I am responsible for stocking contracts for doctrine ships and I want to make sure that I always have a certain number of doctrine ships up on contract. I want to be able to 
1. select all items from one of my contracts in the contracts Tab
2. right click --> stockpile --> add to new stockpile
3. configure stockpile: set multiplier to 10, matching all active, select the station where I want to stock the contracts, include contracts
4. The newly created stockpile should then include all items from the contract with the quantities in which they were included in the contract and not the default amount of "1". Right now if I create a stockpile with this method the stockpile will only contain 1 of each ammunition type that is part of the doctrine fit

Same use-case applies to the ship fittings Tab. (I know I can achieve the desired result by Copy+-->Eve Multibuy and then importing the Multibuy into a new stockpile, but that is a bit of a workaround). Even better would be if we could somehow directly import fits/contracts/?industry jobs? directly into the stockpile tab by using the Import button which currently gives you the Eve Fitting Tool/ISK PerHour/Eve Multibuy/Shopping List/Stockpiles XML/Stockpiles Text import options.

**Comment by jpkoester1** [comment]
I am sure you guys kow better how to implement this but here is my amateur try:
![image](https://user-images.githubusercontent.com/66028066/225892692-aeb7dd51-dc95-4e86-ab0e-eb3700f6c460.png)

**Comment by GoldenGnu** [comment]
That looks good to me. Just to be extra safe I would use `getOrDefault(item, 1)`. (May have to be `1L` If it expects a long)
I really want you to make a PR for it, since you did the feature and that is really awesome!

**Comment by jpkoester1** [comment]
So just as a headsup, this is going to be my first PR ever, so please hang in there with me in case I mess something up...

**Comment by GoldenGnu** [comment]
Released in 7.6.0
