### ISSUE TITLE
Volume Size - 3 tabs

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#369]
Volume size in `Market Orders` & `Transactions` tabs use unpackaged values rather than packaged values.

`Market Orders` & `Transactions` it would be best if they were the packaged weight of the unit being sold.  Since market items **must** to be packaged to be listed in addition to being able to use the proper value to create a fuel cost calculation column.

**Comment by Mr00Anderson** [comment]
Edited out assets tab information.

**Comment by GoldenGnu** [comment]
Released in 7.6.0
