### ISSUE TITLE
Corporation Mining Ledger

### ISSUE THREAD

**Issue by GoldenGnu** [GoldenGnu/jeveassets#371]
Most of the work for this is already done but to finish the feature I need to find a corporation with moon refineries to help test it...

- [x] Character/Corporation filter for the Mining Graph
- [x] Tool for the extractions data
- [x] Testing
- [x] Default filters
- [x] Table colors

**Comment by labrazavr** [comment]
Can we pull data from Singularity? if so i can help putting Ahtanor and test it

**Comment by GoldenGnu** [comment]
Thank you for offering to help!
Sadly, there is no longer a version of ESI for singularity.

**Comment by aixtools** [comment]
How to contact you (in Eve)? Soon we hope to be in NULL-sec again, with moons.

**Comment by GoldenGnu** [comment]
Thank you for offering to help.

The in-game roles required to get the corporation mining ledger data is:
`Accountant` and `Station_Manager`.
Without those roles you can not get the data. In addition to needing in-games roles, someone would have to run a dev build and export an jEveAssets account (not the be confused with an eve account, it only give access to ESI) with the ESI scopes required to get the corporation mining ledger and then share it with me.

That is a huge ask, but, that is what is needed.

**Comment by aixtools** [comment]
How do I go about getting or making a devbuild?

**Comment by aixtools** [comment]
So, some testing of a dev build later:

Two columns to add:
* countdown timer
* _free_text_ aka label so you can mark it as something easy to organize/recognize (eg, R04, R08, Corp-Only, Alliance, etc.

Currently only these columns exist:
![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/82b6a777-7358-41cd-a7f1-b543fde7e772)

Many thx for the new addition!

**Comment by aixtools** [comment]
As to a default filter:
* chunk arrival is before (now - 48 hours) (or natural decay - 48 hours). Why - 48 hours: because that is how long the ORE is in space - roughly.
* color addition: e.g., chunk arrival > 7 days -> green; <7 > 2 days: yellow; (chunk arrival< 2days) && (chunk arrival > (now - 48 hours)) (red).

**Comment by GoldenGnu** [comment]
Released in 7.7.0
