### ISSUE TITLE
Delete/Group multiple stockpiles

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#377]
It would be nice to be able to select and delete more than one stock pile at a time, as well as move them to a new group collectively.

**Comment by GoldenGnu** [comment]
On idea would be to have a delete and group button on the toolbar, that allowed you select stockpiles with the same dialog the shopping list button uses. I'm open to other suggestions

**Comment by Mr00Anderson** [comment]
> On idea would be to have a delete and group button on the toolbar, that allowed you select stockpiles with the same dialog the shopping list button uses. I'm open to other suggestions

Nice simple. KISS they say, keep it stupid simple!

**Comment by GoldenGnu** [comment]
Released in 7.8.0
