### ISSUE TITLE
Stockpile menu overflow

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#381]
![image](https://user-images.githubusercontent.com/1356935/234894426-83bdf14c-2fc6-4835-a24c-08c0bb882fec.png)
This image is significantly truncated. 

As seen above this is unfunctional for me at this point because I have to use two monitors to see the bottom of the list of stock piles because when adding a lot of ship fittings it causes this to happen.

Groups should be added to right click context menu, so that all stockpiles can be seen on screen in the right click context menu.

**Comment by GoldenGnu** [comment]
There is a solution for that, that is used in saved filters menu, that should be able to be reused here.

**Comment by GoldenGnu** [comment]
Released in 7.7.0
