### ISSUE TITLE
Feature Request: Option to Change Line Colours Within the 'Price History' Chart

### ISSUE THREAD

**Issue by JGH174** [GoldenGnu/jeveassets#387]
Having the ability to change the colour of each line within the Price History tab would be a welcome QoL update.

Certain default colours such as yellow & green are difficult to view when using a light theme, conversely other colours become difficult to view when using a dark theme such as blue & purple.

![Price History](https://github.com/GoldenGnu/jeveassets/assets/134204644/7a3e30c1-a587-44ef-b4ac-097237abd22a)

Thank you

**Comment by GoldenGnu** [comment]
Could a solution be to automatically select colors, depending on the theme, that are easy to see?

**Comment by JGH174** [comment]
> Could a solution be to automatically select colors, depending on the theme, that are easy to see?

That would be a good solution. Colours which standout enough from each other but also standout from the graph background if possible.

**Comment by GoldenGnu** [comment]
Released in 7.7.0
Options in Settings > Color (off by default)
