### ISSUE TITLE
Industry Jobs: Active Filter - bug

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#388]
I am new to jeveassets - so maybe the bug is user error : p

a) I did not recognize 'load' as starting points for filters (feedback, not bug)
b) I tried to create and name a filter 'Active' - which it would not (won't overwrite a default filter - which got me to Load)
c) loaded the default filter - and it is slightly different from what I created - and, imho, bugged. Why? Cancelled is not 'Active' - a cancelled job is also a 'returned' job, just no results delivered. Perhaps there is a 'pause' - I have never tried to pause a job.
d) further while not a bug - naming the column 'Completed Date' to Delivered Date would make it, imho, a lot clearer about what it is used for.
e) question (in BR are bad, but here goes anyway) - does the ESI include a column 'Delivered by'?

**Comment by aixtools** [comment]
Same idea - market orders - 'cancelled' orders are not 'Active'

**Comment by GoldenGnu** [comment]
A) I’m open to suggestions to improve it.
B) Yes, you can not overwrite default filters, given there are only 2-4 default filters total, I find it fine to have those restrictions. 
C) Yes, that sounds like a bug.
D) Contracts are not always delivered at the end, it depends on the contract type.
E) ?

**Comment by aixtools** [comment]
d) this is not about contracts - but factory jobs.
e) in a corp, jobs can be delivered by someone other than the submitter.

**Comment by GoldenGnu** [comment]
Okay, so having multiple things in a single issue is super confusing. So please make separation issues for C and E (it is in ESI, so, super easy to add) and A (if you know how to improve it) and keep any new issue to one thing per issue (create as many as you like, this is perfectly fine). I’m going to close this issue to make room for the new ones. Thank you very much for your feedback and bug report, much appreciated!  :)

**Comment by aixtools** [comment]
roger.
