### ISSUE TITLE
JRE support

### ISSUE THREAD

**Issue by TyrHeimdalEVE** [GoldenGnu/jeveassets#393]
Hi,

In regards to the [Wiki and requirements for JRE](https://wiki.jeveassets.org/faq#how_to_run), the following is listed:
> Oracle Java Runtime Environment v8, or
> Adoptium Temurin™ v11-LTS

Is this version requirement outdated? I seem to have no issues running this on [jre-openjdk 20.0.1](https://archlinux.org/packages/extra/x86_64/jre-openjdk/).

Want to clarify to avoid having dependencies on older JRE for no good reason.

**Comment by GoldenGnu** [comment]
I more accurate requirement listing would be Oracle Java 8 or any later version. However, on windows the newest JRE is Java 8, because, Oracle stopped releasing JREs for newer version. On Linux that isn't a problem. I think mac is the same as windows, but, I'm not sure.

**Comment by TyrHeimdalEVE** [comment]
Thanks for the reply. They just combined them both in the JDK's from Java 9+ and tried to shake down people for using it commercially. You can still download them from: https://www.oracle.com/java/technologies/downloads/#jdk20-windows

While I do not condone installing Oracle software (any software, speaking/doing business with or even mentioning their name), I'm not sure what the best course of action would be.

For me, I only care about AUR package users and so requiring jre-openjdk will seemingly suffice, but it would be great if you with the most insight into the code, know if there is any technical reason it wouldn't run on alternative JRE's. The only thing I could think of would be if some assets were used that is proprietary and only included in Oracle's stuff.

Additional info: https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b

**Comment by TyrHeimdalEVE** [comment]
Cheers, thanks! I'll pin the post on AUR and follow up if users report any issues.

**Comment by GoldenGnu** [comment]
I updated the bit on the wiki:
https://wiki.jeveassets.org/faq#requirements
I hope it's a little easier to understand now?
