### ISSUE TITLE
Industry Jobs: default filter 'Active' includes cancelled jobs  - and more

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#399]
This filter should only show jobs that the ingame UI would show as 'In Progress' or 'Ready for Delivery'. Currently is shows the in game status: _In progress_, _Ready for Delivery_, and **_Cancelled_**

So, since there are already two default filters I would prefer to see 4 (or 5) filters - that reflect the ingame names and choices:

![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/8eb77539-b12c-4ed8-be56-a501d0c848ff)

* All Active - what Active currently attempts to show, except it includes halted (state != Delivered && state != Cancelled)
* In Progress (state is 'Active')
* Ready for Delivery (state is 'Done')
* Halted (state is Cancelled ??) - _in game this option does not show anything. Perhaps best to skip it!_
* History - is what _Completed_ shows (while I was expecting this filter to show 'Ready for Delivery' (state is 'Delivered')

**Comment by GoldenGnu** [comment]
I'm going to update the existing filters, I'm not going to add new filters. I generally don't believe in default filters is a good thing. So, I will keep and update/fix what is currently there, but, I really don't want to add new ones.

**Comment by GoldenGnu** [comment]
Released in 7.7.0
