### ISSUE TITLE
UI: Options: Market Prices: defaults

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#400]
When trying to setup default prices - the last day is often not a good parameter.
* Would like to see a number of days to 'average' the price (one of the dialogs let you set a number of days, asin general and 'transaction age.
* would like the 'options:market prices' labels to match (more closely) the EveUI (see picture) - Avg/Average, rather than mid-point
![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/e42c0542-c354-484d-b8cb-23c6c6996e11)
because mid-point - to me - means mid-point between lowest sell, and highest buy. On items with extreme values (eg low activity) mid-point can be way off (e.g., highest buy is 1.00 while lowest sell is 101 (or much more). Basing it on actual sales over X days is much safer.
* Also, only present a price when there has been minimum quantity or minimum # of orders

![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/d773f0e7-c10e-427d-b45e-620126908566)

When conditions are not met - set to zero (easy to set a filter to exclude entries where price is zero)

* imho: having this right will make the 'reprocessing' tab more accurate and safer to use.

**Comment by GoldenGnu** [comment]
Please make issues for each feature request separately, having more than one thing in an issue is very bad.
I'm going to close this issue now, so please, create new issues for each of your suggestions.

**Comment by GoldenGnu** [comment]
So, this might seem a bit harsh to just close the issue. I do appreciate your feedback and suggestion very much! The reason each issue need to be only one suggestion, is so I'm able to track progress. If I do one of the things in you suggest in this issue, the issue will end up in a limbo state of being x% done, but, not closable, which is really confusing and can lead to some of the suggestion being forgotten, which is super bad.

**Comment by GoldenGnu** [comment]
> Would like to see a number of days to 'average' the price (one of the dialogs let you set a number of days, asin general and 'transaction age.

jEveAssets get the price pre-calculated, so that is not possible 

> means mid-point between lowest sell, and highest buy

And that is exactly what that price is

> Also, only present a price when there has been minimum quantity or minimum # of orders

Again, not possible because the prices are not calculated by jEveAssets 

So none of the suggestion are possible
