### ISSUE TITLE
UI: Assets listing: Container (and likely more) - option to toggle 'show' itemID

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#401]
In the _Container_ text the **itemID** is always included. This, imho, does not add vital information for most cases.
Having an option to include it could be helpful with some filters - so I don't want to see it goAway forever, but I'd rather not clutter my table with a (for human readable text) unnecessary large/long integers.
* here it is included, but does't really tell me anything (adding _Location_ will give me the info I need)
![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/5857096c-4822-4ca9-b6b9-bd39ee995cfe)
* here, assuming _Location_ or _System_ is showing elsewhere - this tells me where to go, but the added _Integers_ does not make the result more clear
![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/b8adb9ac-5dd9-4d2d-a26a-7f6194895482)

* Please make displaying the **itemID** an option, or toggle
* Also nice: when not 'None' perhaps add the 'Flag' field value, e.g., 'Agents (3rd Division)', or 'Hangar', or 'Rig Slot 2'

**Comment by GoldenGnu** [comment]
The long values allow you to filter on that container and everything inside by using contains. Without the itemID that isn’t possible. I agree it’s ugly and it may be worth simply removing it from display, will still keeping the filterable value. I will look into that

**Comment by aixtools** [comment]
Simply removing it from display sounds like an option. I have to think a bit about how to write a filter using "contains".

**Comment by GoldenGnu** [comment]
Released in 7.9.0
