### ISSUE TITLE
Add the option to see Contracts without grouping by contract

### ISSUE THREAD

**Issue by ebjay** [GoldenGnu/jeveassets#402]
The items in the Contract tool are grouped by contract Description. Sorting works only within groups. Currently it is not possible to sort globally. 
Please provide an option to display contracts as a flat table without grouping.

**Comment by GoldenGnu** [comment]
I'm going to close this in favor of #374. I finally figured out how to make sorting work in the contracts tool.
Please leave a comment if you still think it this feature could be useful.
