### ISSUE TITLE
Stockpile --> Shopping list does not respect Contracts "Matching all" settings

### ISSUE THREAD

**Issue by jpkoester1** [GoldenGnu/jeveassets#403]
Shopping list with contracts "match all" activated leads to mismatch between the stockpile window and the resulting shopping list. Please note that Nanite Repair Paste is not included in the shopping list:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/b06f7f35-c0e8-4aef-ae17-a3882d3fadf6)

if matching all is disabled the shopping list is exactly the same and matches the stockpile window:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/9c1a6125-d0b6-4367-a460-158519e1bf69)

**Comment by jpkoester1** [comment]
looks like StockpileShoppingListDialog.java Line 284 iterates through all contract items no matter what the setting regarding "Match all" is.

**Comment by GoldenGnu** [comment]
- [ ] StockClaim and StockItem store matching contractIDs.
  - [ ] StockClaim.matches() check contractIDs
  - [ ] StockClaim.compareTo() sort matchAll first

**Comment by GoldenGnu** [comment]
Released in 7.7.0
Now also works with subpiles
