### ISSUE TITLE
Assets view: **Type Count** ignores filter setting

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#405]
Bug: (imho)

My best guess is that the **Type Count** column is the total of the **Type**, but of all records, rather than only the selected records. e.g., from the following I would expect **Type Count** to say `10` rather than > 200M.

![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/44de8dce-e50a-48f2-80f4-7109b9255083)

If my best guess is wrong - please explain.

**Comment by GoldenGnu** [comment]
Yes, that is exactly what it is - total of all assets of that type (and everything else included in the assets, like jobs, orders etc.). I don't see why that would be a bug?

**Comment by GoldenGnu** [comment]
There are plenty of ways to see the count of shown items: The status bar, the right click menu on a selection or on the column header. All those does that perfectly well. So I’m close this
