### ISSUE TITLE
UI: type count seems to be global, not based on filtered selections

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#407]
I thought I had already create an issue. If so, delete one or the other as duplicate.

A simple example:
![image](https://github.com/GoldenGnu/jeveassets/assets/10852597/c7afc0e7-5063-4026-85f9-90c84ae806c8)

I would expect the `type count` column to be 2420 (ie, 240+2180). Especially since my totals includes multiple accounts - and, atm, I am focused on seeing data from one account.

**Comment by GoldenGnu** [comment]
#405
