### ISSUE TITLE
BPOs in Stockpiles need to be handled differently from other Assets

### ISSUE THREAD

**Issue by ebjay** [GoldenGnu/jeveassets#411]
The BPOs added to the Stockpiles should not use the Stockpile multiplier, just the Target multiplier. Adding a BPO to a Stockpile is a reminder to acquire and research the BPO (red) or that the BPO is in stock and ready to make copies (green). Only the Target number of BPOs is required (usually 1.00). Multiplying the Target number by the Stockpile multiplier unnecessarily bumps the status to red while the BPO stock is usually static.

**Comment by GoldenGnu** [comment]
The way this is going to be implemented is that all stockpile items will have an option to ignore multiplier.
Checking the options will completely ignore both stockpile and subpile multiplier.

**Comment by GoldenGnu** [comment]
Released in 7.8.0
