### ISSUE TITLE
Bug: Materials added to stockpile through blueprint are rounded up

### ISSUE THREAD

**Issue by RichterL** [GoldenGnu/jeveassets#413]
[link to discord thread](https://discord.com/channels/565306310229229569/565306310229229571/1146400686259572786)

Adding blueprint materials to a stockpile is rounding up (and it probably shouldn't as the calculated "target" column rounds up itself...Steps:
1) select blueprint from assets, right click, add to stockpile, select as materials, ME10, T2 rigs, nullsec, medium structure
2) there is no #runs option so it gets inputed as 1-run (that's fine as long as it doesn't round the values - which it does)
3) go to lazy-blacksmith (which shows the adjusted amounts before rounding up) and select the same BP
4) repeat 1) as a new stockpile, manually change the values in editable Target column to those from lazy blacksmith
5) both stockpiles have the same amounts in computed target column despite having different values in manual target column (correct). Change the multiplier to higher value or add stockpile as a subpile with higher multiplier - the rounding "error" is now affecting the computed target column and showing incorrect values for the auto-inputed stockpile

![1-run](https://cdn.discordapp.com/attachments/1146400686259572786/1146400930128986192/image.png)

![10k-run](https://cdn.discordapp.com/attachments/1146400686259572786/1146401265157414983/image.png)

**Comment by GoldenGnu** [comment]
Released in 7.8.0
