### ISSUE TITLE
Different color for orders outbid by your own orders

### ISSUE THREAD

**Issue by Joel861** [GoldenGnu/jeveassets#416]
Make it possible to the program recognize your own market orders for the same item to sell or buy that are not in front of the Que.
This way if i have multiple buy or sell orders it doesnt get flashed as outdated for the same item. this will make it faster to update orders for everyone.

Also another cool feature would be if it was possible that the programs recognizes regional BUY orders que. this way it wouldnt flash as red if my order was the first regional order but at a lower price on the que. it would save a lot of time for everyone.

**Comment by GoldenGnu** [comment]
> Also another cool feature would be if it was possible that the programs recognizes regional BUY orders que. this way it wouldnt flash as red if my order was the first regional order but at a lower price on the que. it would save a lot of time for everyone

Please don't put multiple feature suggestion in a single issue. Please make a new issue for the above.

**Comment by GoldenGnu** [comment]
Released in 7.8.0
