### ISSUE TITLE
Question (or Enhancement?): how to use 'regular expression' to calculate a relation between columns

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#419]
An example:

Sometimes a max buy price is 1.00 (because noone is seriously buying - hoping for an unattentive seller) - while the lowest sell price is - for simplicity - 100.00 - a 100% spread.

I would like to be able to calculate the ratio/difference between two columns (e.g., minSell/maxBuy) (and maybe add *100(%) to convert to %).

So question: how to do this using regular expression - if possible.

If not possible, please consider as an enhancement.

**Comment by GoldenGnu** [comment]
I also think this could be done using a formula column.
1) Table > Formula Columns > Add
2) Select a name
3) Formula `[Sell Min] / [Buy Max] * 100`

Does that resolve the issue for you?

**Comment by GoldenGnu** [comment]
I'm going to close this as resolved, as a solution have been presented and there is no reply from the user.

Feel free to comment on this issue, if you want it re-opened.
