### ISSUE TITLE
Enhancement: Options for '% Reprocessed' calulation

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#420]
Currently `% Reprocessed` is coded as `Reprocessed` / `Price` * 100. 

I would also like to 'option' to have it be `Reprocessed` / `Manufacturing` * 100.

Or - maybe better: along the line of #419 - be able to define a column (rather than a search criteria) based on existing columns (ie, make my own '% Reprocessed') - and, to keep it distinctive from standard columns - be able to define a background color for self-defined columns.

**Comment by GoldenGnu** [comment]
I feel like that would be super easy to do with a formula column.
1) Table > Formula Columns > Add
2) Select a name
3) Formula `[Reprocessed] / [Manufacturing] * 100`

**Comment by GoldenGnu** [comment]
I'm going to close this as resolved, as the user never replayed to the follow up question
