### ISSUE TITLE
Tags menu overflow

### ISSUE THREAD

**Issue by Knicpaw** [GoldenGnu/jeveassets#422]
When right-clicking to attach a Tag to an Asset, if the list of Tags is larger than the available window/screen space, the bottom of the list is unviewable/unselectable.

The Tags pop-up requests a scrollbar to be added, if possible keeping the "+ Add tag..." at the top so it is always an available option.

Alternatively, the ability for the tags pop-up to tile multiple pages of tags... but again, given a large list of tags, this may run out of real-estate.

Thank you.

**Comment by GoldenGnu** [comment]
Released in 7.9.0
