### ISSUE TITLE
Keep history of industry jobs

### ISSUE THREAD

**Issue by EdThelleres** [GoldenGnu/jeveassets#425]
Everytime industry jobs get updated, all get deleted and replaced by newly pulled data. ESI allows only a limited data for industry jobs so we are losing the older jobs from jEveAssets.

Feature request: don't purge the data with each pull, instead keep the old and update with new data. That way we can keep extensive history of industry jobs.

**Comment by GoldenGnu** [comment]
Released in 7.9.0
