### ISSUE TITLE
Critical error when opening old data (profiles) after 5.4.3 update

### ISSUE THREAD

**Issue by afraga-br** [GoldenGnu/jeveassets#43]
![jea bug](https://user-images.githubusercontent.com/5174016/38785491-2750c5dc-40f7-11e8-9b22-e05794bbc479.png)

It started happening right after 5.4.3 update.

**Comment by GoldenGnu** [comment]
Thank you for you bug report and including the BugID, making it really easy to find the stack trace in the bug database.

It looks like your settings are corrupted or you have been running a costume build, either way, you will need to send me your profile files, so, I can reproduce the error and debug it.
1) Go to the settings location ([help](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#settings-location))
2) Zip the `profiles` directory
3) Email the zip to niklaskr@gmail.com
❗️ Do not upload the profiles filed here or any other public place, those contain sensitive information.
4) I will look into it as soon as I have the profile files :) 

Stack trace for reference :
https://eve.nikr.net/jeveassets/bugs/#bugid664

**Comment by afraga-br** [comment]
Hi, you are right, it was not a problem with stock JEA, it was because of a custom build.
Thanks a lot for the quick answer!
