### ISSUE TITLE
Stockpile "target" column acts weird when resized

### ISSUE THREAD

**Issue by shiek403** [GoldenGnu/jeveassets#431]
the resizing of the target window in the stockpile does WEIRD stuff
like, I would think "oh its truncating to … because it doesn't have space"
BUT if I make it WIDER, it actually truncates MORE (see pic 2 on discord)
and if I make it SMALLER it truncates LESS (pic 3) and actually shows all the data I want to see... but cuts off the actual values lower

**Comment by GoldenGnu** [comment]
Released in 7.9.0
