### ISSUE TITLE
Question: Move to Kotlin + Gradle

### ISSUE THREAD

**Issue by NoUsernameProvided** [GoldenGnu/jeveassets#433]
Hey, would you consider migrating to Kotlin and Gradle? It can be done gradually.
I'm considering to either forking the project and develop in parallel or help with the main project instead.

**Comment by GoldenGnu** [comment]
Could you explain what benefits jEveAssets would get by migrate to Kotlin?
You're more than welcome to contribute, that is always very welcome.
jEveAssets is open source, so you can always fork and make your own version, if you like.

**Comment by GoldenGnu** [comment]
I'm going to close this as resolved, as the user never replayed to the follow up question
