### ISSUE TITLE
Flatpak distribution of jEveAssets

### ISSUE THREAD

**Issue by Nathan-LS** [GoldenGnu/jeveassets#434]
Hi!

I put together a project at [https://github.com/NullsecSpace/io.github.GoldenGnu.jEveAssets](https://github.com/NullsecSpace/io.github.GoldenGnu.jEveAssets) to publish jEveAssets as a Flatpak on [FlatHub.org](https://flathub.org/). Flatpak apps are easily distributed as sandboxed applications on Linux and an introduction to Flatpak is available [here](https://docs.flatpak.org/en/latest/introduction.html).

Can I publish this on FlatHub.org? You can also fork my repo and publish the app following the steps in the [submission guidelines](https://docs.flathub.org/docs/for-app-authors/submission/) as Flathub prefers apps to be published by their developers.

Thanks!

**Comment by GoldenGnu** [comment]
You're free to redistribute jEveAssets under the GNU general public license, version 2 or any later version.

I only make releases on GitHub and via the auto update. I'm not interested in maintaining distributions elsewhere.

I would like to point you to the follow issue: https://github.com/GoldenGnu/jeveassets/issues/63 that allow you some extra options as a packet managers - if you need additional options, please let me know and I will see what I can do.

I'm going to close this issue as completed, but, if you need anything else if regard to the redistribute, please, post it in this issue.

**Comment by Nathan-LS** [comment]
Thank you, jEveAssets was published successfully on [FlatHub](https://flathub.org/apps/io.github.GoldenGnu.jEveAssets) allowing it to be packaged once and usable on practically any Linux distro.

I did open a [PR](https://github.com/GoldenGnu/jeveassets/pull/435) as some of the files in the Flatpak repo were requested to be added to upstream.

Also, from my browsing it appears no versions of the app icon exist that are larger than 64x64, even from the original in the [SDE  icon pack](https://developers.eveonline.com/resource) unless you know of a larger png or SVG.
