### ISSUE TITLE
Lock the Tabs

### ISSUE THREAD

**Issue by shiek403** [GoldenGnu/jeveassets#438]
can we get an option to lock the current tools tabs? I find myself more than once going to open a tab, and accidentally clicking an X. if we could get a setting where I can take those X's away, and if I ever decided to edit it later I can unlock it?

**Comment by ScyllPoesis** [comment]
Would love to have a lock feature as well. Always a sad time when I click too quick and have to go down the tree to reopen a tab.

**Comment by GoldenGnu** [comment]
Released in 7.9.0
