### ISSUE TITLE
Feature: A way to work with Date columns

### ISSUE THREAD

**Issue by lnickersl** [GoldenGnu/jeveassets#439]
I wanted to make a column that tracks how much volume an order makes per day.
But currently there is no way to work with date columns from what I can tell, can you please make a “**Days Since Issued**” column or “**now()**” function and some way to work with date columns as an Int?

**Comment by GoldenGnu** [comment]
I'm going to add date values to formula columns, as that seems like the most flexible solution.

Dates will be represented by days from now.
10 days in the future will be `10`.
10 days in the past will be `-10`
Today will be `0` (zero)

Here is an example formula column with the average items sold/bought per day:
`([Quantity Total] - [Quantity Remaining]) /  if([Expires] < 0,max(1,[Expires]-[Issued]),abs([Issued]))`

Any feedback or suggestion to improve on this concept is very welcome

**Comment by GoldenGnu** [comment]
Released in 7.9.0
