### ISSUE TITLE
Industry jobs display in inventory tree

### ISSUE THREAD

**Issue by mandjevant** [GoldenGnu/jeveassets#440]
Industry jobs in tree inventory are incorrectly displayed.

To reproduce:
In eve
- Start manufacturing from BPC.
- Start manufacturing from BPO.
- Start reaction from reaction blueprint.

In JeveAssets Tools > Inventory > Tree
Filter: Flag Contains "Industry Job".

Notice:
Regardless of how many runs your industry job is, the value and information are always displayed for a single run.

Expected behavior:
Display information based on the amount of runs in the industry job. 

Discovered with help of @shiek403

**Comment by GoldenGnu** [comment]
Are you still able to reproduce this with version 7.9.0?

**Comment by mandjevant** [comment]
In version 7.9.0 it is unclear to me what the manufacturing column displays.

For example, a flycatcher bpc that is manufacturing with 4 runs shows a manufacturing value of 7.793.140
This value does not correspond to the job cost for 4 runs or 1 run. Nor does it correspond to the input, output or profit. 

I can not track what it does represent.

**Comment by GoldenGnu** [comment]
Check the column ToolTip
