### ISSUE TITLE
Stockpile Low-water mark

### ISSUE THREAD

**Issue by ScyllPoesis** [GoldenGnu/jeveassets#441]
Hello!

Relatively simple request here, but as I've started testing out a stockpile-based industry workflow I've found jEVE fits perfectly into my system, and so I've been tinkering with it and exploring all the cool things it can do beyond just asset/wealth tracking.

One thing that would be a great addition to the stockpile "Red bad Green good" UX is if we could define a low-water mark for a stock, and introduce a middle "Yellow" state for stockpiles. In practice, this would result in "Red bad Yellow warning Green good" ooga booga mindset. Yellow stockpiles are stockpiles that are diminished or otherwise in need of review, but perhaps not urgently.

Ex:
A stockpile of various minerals or components for a production pipeline, with a low-water setting of 50%.
- If all stocks are above the target, the stockpile is green, same as current.
- If any stock is below target, but all stocks are above the low-water setting, the stockpile is yellow.
- If any stock is below the low-water mark (50%), the stockpile is red, same as current.

**Comment by GoldenGnu** [comment]
That is already possible:
Options > Options… > Stockpile
Allow you to set up two or three zones in percent.

**Comment by ScyllPoesis** [comment]
Wow, excuse my ignorance. This tool is incredible, always something new to find. Thanks for the tip!
