### ISSUE TITLE
Ability to hide subpile list

### ISSUE THREAD

**Issue by ScyllPoesis** [GoldenGnu/jeveassets#442]
Am still loving this tool for organizing rolling-stock industry (up to a couple hundred stockpiles now). So my eternal gratitude to the developers and maintainers. 🙏 

One thing that would be a great QoL feature for madmen like me would be to be able to show/hide the subpiles listed under a stockpile. 

For ex, I maintain separate groups of stockpiles (minerals, PI, reactions, etc.) for each product line (Orca - Minerals, Orca - Reactants, etc.), and then subpile them all into one overall stockpile for each group (Overall - Minerals). When I'm maintaining stocks for multiple lines, each of these overall stockpiles might have up to a dozen subpiles, which adds to a lot of extra lines that I don't need most of the time, and so would save me a good amount of space if I could hide those. Thanks in advance for the consideration!

**Comment by GoldenGnu** [comment]
Released in 7.9.0
