### ISSUE TITLE
Asset Value of manufactured items Calculated incorrectly

### ISSUE THREAD

**Issue by MagnarTW** [GoldenGnu/jeveassets#444]
when calculating asset value it is currently calculated incorrectly.

Example: I have a 5 run typhoon job running.

Asset value is calculated as follows:

tag "Manufacturing" = 5 x typhoon value 
tag "Industry Job" = 1 x typhoon value

Total asset value shown = 6 x typhoon value

**Comment by GoldenGnu** [comment]
Released in 7.9.0
