### ISSUE TITLE
Stockpile: Matching all for assets

### ISSUE THREAD

**Issue by jpkoester1** [GoldenGnu/jeveassets#446]
I am looking for a way to set up stockpiles of fitted ships.

Lets say I want to stock 20 doctrine Drake fits, the stockpile should tell me how many Drakes with that specific fit I have in the selected locations. All fits with other ships should be ignored.

For contracts a similar feature exists by using the "Contracts --> matching all" option.

I would like to request a "Fit --> matching all" option that would basically treat each fitted ship in the hangar similar to a contract in the "contracts --> matching all" feature. Basically the program would check all ship fits to see if all items from the stockpile are included in the fit in the required amounts. If so then the fit will be counted towards the stockpile total. If not the fit and all its components are ignored with regards to the stockpile.

**Comment by GoldenGnu** [comment]
Released in 7.9.0
