### ISSUE TITLE
The ability to have one column that allow us to have excel formulas.

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#45]
For example in stockpile, were i manage corp fuel logistics, i use the data from stockpiles to see how long the materials lasts (in days).

I take the data and ad them to excel to see for example that i have enough Robotics that will fuel our structures for a certain amount of days.

If a column can have the ability to have formulas then excel is not needed.  

I am not a coder so i dont know if this is easy or not, but if the basic excel formulas can be added to a "formula column", then that would make this app even better.

**Comment by GoldenGnu** [comment]
I feel like formulas are too much to implement. But, I have an alternative idea. That if you could set “consumed each hour” for each item in the stockpile and then jEveAssets would show you how much time was left?

**Comment by GoldenGnu** [comment]
It would be a new feature, that I would have to code.

After thinking a bit more about it.

They way I want to implement it:
In each stockpile settings, you select `time` or `quantity`
If `quantity` is selected, the stockpile would work as it does now.
If `time` is selected, It would allow you to set a target time period in hours/days/months (This would determine the color coding of each item in the stockpile).
Then the `target` for each item in stockpile would be used as "consumed each hour".
In the table it would show you how much time is left for each item and the total would show the time when the tower runs out of the first type of fuel.

I hope that makes sense. I'm not very good at explain it...

**Comment by GoldenGnu** [comment]
Possible solutions:
https://stackoverflow.com/questions/3422673/how-to-evaluate-a-math-expression-given-in-string-form

**Comment by GoldenGnu** [comment]
Options:
http://javaluator.sourceforge.net/en/home/
https://github.com/Shy-Ta/expression-evaluator-demo
https://github.com/uklimaschewski/EvalEx
https://github.com/mariuszgromada/MathParser.org-mXparser

**Comment by GoldenGnu** [comment]
Going to use the EvalEx library, as that appears to be the most active one.

ToDo:

- [x] Add column
- [x] Remove column
- [x] Edit column
- [x] Save/Load columns
- [x] Update expressions on data change
- [ ] Save/Load column position 
- [ ] Export/Import filter with formula column
- [ ] Update filters with new/removed/edited columns
- [ ] Migrate JMenuJumps
- [ ] Buttons:
  - [ ] Mathematical Operators
  - [ ] Boolean Operators
  - [ ] Function

**Comment by GoldenGnu** [comment]
Released in 6.9.0
