### ISSUE TITLE
UI request: Price History scaling based on objects selected

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#466]
Currently the left scale (price) seems to be scaled by the most expensive item in the list, regardless if it is selected, or not.

So, if you are wanting to look at the price of a capital, and also other materials (that rarely get about 20k - while the graph draws nicelt, the left scale is just 0.0B over and over again. Only after removing the most expensive item from the list does the graph begin to re-scale the left axis.

Thx!

**Comment by GoldenGnu** [comment]
Released in 7.9.1
