### ISSUE TITLE
Stockpile Target Truncation issue (fixed on non-subpiles but subpiles still truncating weird)

### ISSUE THREAD

**Issue by shiek403** [GoldenGnu/jeveassets#467]
a followup to #431 ( and I have verified I am running 7.9.0)
now all the normal target fields truncate and fill correctly, but the subpile multiplier still shows "… "unless you shrink the window in which case it starts filling in the numbers but then the target numbers are too small
![Screenshot 2024-06-01 083523](https://github.com/GoldenGnu/jeveassets/assets/69616189/641de578-16e7-4aea-8f4c-b7a75aa88295)
![Screenshot 2024-06-01 083438](https://github.com/GoldenGnu/jeveassets/assets/69616189/b1cb2edb-0801-475e-b21a-c4e57791bc90)
the ones with the pencil edit guy are all just … when there is definitely enough space to show the number, and the weird part is the shrinking, if you shrink the column, it actually starts to show the number :)

**Comment by GoldenGnu** [comment]
Do you have auto resize of columns enabled?

**Comment by shiek403** [comment]
I did, and I played with all the options
that's how I found that by clicking "disable" and then resizing it manually, if you squish the numbers, the "…"'s slowly become the actual numbers, but only when squished very small

**Comment by GoldenGnu** [comment]
I'm not able to reproduce it. What are your OS, java version and java vendor?

**Comment by shiek403** [comment]
oh interesting! I love a good un-reproducible!
Win 10, 1.8.0_411-b09 and oracle's java 
if it's just a me problem I'll stop complaining :) 
so it only shows up on the areas with the edit icon for me, all the others scale correctly, but ones with the edit icon act in such a way adding more screenshots to show what I'm seeing
OH! and in playing with it, I managed to make the edit pencil to sneak away as well! 
![Screenshot 2024-06-01 104317](https://github.com/GoldenGnu/jeveassets/assets/69616189/6e63c24d-00d8-434b-8c06-dec49dd39135)
![Screenshot 2024-06-01 104153](https://github.com/GoldenGnu/jeveassets/assets/69616189/9c90f029-7505-4c47-a49d-7b109e5303ef)
![Screenshot 2024-06-01 104132](https://github.com/GoldenGnu/jeveassets/assets/69616189/d967ed55-11bd-48b0-9d04-385d7cbafe19)
![Screenshot 2024-06-01 103929](https://github.com/GoldenGnu/jeveassets/assets/69616189/d2253be5-6f1f-49f9-bdea-50e9da17908b)

**Comment by GoldenGnu** [comment]
I don’t think just you, I didn’t mean to insinuate that. However, I will need to figure out what trigger the bug to fix it.

**Comment by shiek403** [comment]
I only see it on fields with the pencil. if that helps
if there is anything I can do to help or any files I can upload or show just let me know :)

**Comment by GoldenGnu** [comment]
I think I have found the bug, however, since I'm not able to reproduce it myself, I would like you to try a dev build with the fix:

**Super important** dev build info:
https://wiki.jeveassets.org/devbuild (please, read it - it's very shot)

**Download:**
https://eve.nikr.net/jeveassets/jeveassets-7.9.1-dev1-stockpile-target.zip

**Comment by shiek403** [comment]
Unfortunately I still have the truncating and can make the pencil float away even on the new dev build.

**Comment by shiek403** [comment]
Wait I might be on to something
went back to prod 7.9, and went to colors and look and feel in the options, and turned off flat dark, and went back to defaul(windows), and its gone! I can't make it happen. but when I switch to the "flat dark" or "flat dracula" it comes back! hope that helps!

**Comment by shiek403** [comment]
in fact, having gone through them, I can recreate this bug on ALL the flat options, and NONE of the options that DON'T say flat :)

**Comment by GoldenGnu** [comment]
I'm still not able to reproduce it, could you take a screenshot of the entire jEveAssets window with the stockpile tab open showing an entire stockpile with the target `...`, in the dev build

**Comment by shiek403** [comment]
Sure thing!
also adding the shots where I "fix" it by changing the style, and what my current looks are in case that helps.
![Screenshot 2024-06-02 103532](https://github.com/GoldenGnu/jeveassets/assets/69616189/04ea5a16-5217-43b3-9662-7e7c5940b2a3)
![Screenshot 2024-06-02 102825](https://github.com/GoldenGnu/jeveassets/assets/69616189/b89b8496-3549-4c0d-967d-a4fa03567ef0)
![Screenshot 2024-06-02 102732](https://github.com/GoldenGnu/jeveassets/assets/69616189/470ca550-baf3-4214-9d45-a5ea21d4cf67)
![Screenshot 2024-06-02 103212](https://github.com/GoldenGnu/jeveassets/assets/69616189/dd003e53-b8cd-4172-a0a2-e472188f1d7f)

**Comment by GoldenGnu** [comment]
Thank you! I think it may be a caching issue for the width of the target column. It’s going to require a bit of a refactoring to work around. I hope I can get time to do it tomorrow, but, we’ll see. I’’ll post here when it’s done and I have something new for you to test. Thanks you very much for working with me to figure this out.

**Comment by GoldenGnu** [comment]
This _should_ fix the bug (hopefully for real this time).

**Super important** dev build info:
https://wiki.jeveassets.org/devbuild (please, read it - it's very shot)

**Download:**
https://eve.nikr.net/jeveassets/jeveassets-7.9.1-dev2-stockpile-target.zip

**Comment by shiek403** [comment]
lol I must REALLY have something brokenon my end... cause yeah its still there...
Squished to Show numbers
![Screenshot 2024-06-03 082801](https://github.com/GoldenGnu/jeveassets/assets/69616189/9c0e709d-c45c-400f-9d93-4bf045a20a09)
auto size
![Screenshot 2024-06-03 082728](https://github.com/GoldenGnu/jeveassets/assets/69616189/55204ed1-f447-4b8f-8f71-e572c672a41e)
extra wide
![Screenshot 2024-06-03 082707](https://github.com/GoldenGnu/jeveassets/assets/69616189/65f21edf-6608-43a0-9d87-147871e950b9)

**Comment by GoldenGnu** [comment]
Two build to try this time. I'm quickly running out of ideas, so hopefully one or the other will work.
Thank you for helping me fix this complex issue

**Super important** dev build info:
https://wiki.jeveassets.org/devbuild (please, read it - it's very shot)

**Download:**
https://eve.nikr.net/jeveassets/jeveassets-7.9.1-dev3-stockpile-target.zip
https://eve.nikr.net/jeveassets/jeveassets-7.9.1-dev4-stockpile-target.zip

**Comment by shiek403** [comment]
I am actually having quite a bit of fun testing them :)
but unfortunately... neither of them fixed it. I'm REALLY hoping there isn't something specific about my build/puter/something that is causing it and we are chasing an issue exclusive to me...
![Screenshot 2024-06-03 104750](https://github.com/GoldenGnu/jeveassets/assets/69616189/c6a9c262-8c11-48b2-8f61-473bce5bcb6b)
![Screenshot 2024-06-03 104554](https://github.com/GoldenGnu/jeveassets/assets/69616189/662fc05a-0fb2-4af9-8124-c13d79b71961)

**Comment by GoldenGnu** [comment]
I’m afraid, will probably have to be able to reproduce it to actually fix. If you’re will to share your settings I think that will have to be the next step.

In the `data` directory in the [settings location](https://wiki.jeveassets.org/faq#settings_location) find the `settings.xml`, zip it, and email it to me at [niklaskr@gmail.com](mailto:niklaskr@gmail.com)

Hopefully I will be able to reproduce and figure out what is happening, because, I’m pretty lost ATM

**Comment by shiek403** [comment]
Sent :)

**Comment by GoldenGnu** [comment]
I'm not able to reproduce it.

I would suggest uninstalling all version of java and downloading the latest version from [java.com](https://www.java.com)

**Comment by shiek403** [comment]
FUN! thanks for trying! gives me hope that on my next PC it will be fixed, and for now its not like it's a gamebreaking bug or anything! 
I did as you recommended and unfortunately even with fresh java installs, it seems to still persist! but I'll just live with my "…"'s till I get a new build!
thanks again! love the app!

**Comment by GoldenGnu** [comment]
Thank you for the kind words - I'm sorry I wasn't able to fix it. Ofc. if I'm ever able to reproduce I will do what I can to fix it.
I will include the fixes in the next release, as I do think there was at least some bugs in the current code.
