### ISSUE TITLE
Request: Allow "Unknown Location" in Stockpile

### ISSUE THREAD

**Issue by colcrunch** [GoldenGnu/jeveassets#47]
I keep most of my minerals and blueprints and such in citadels (and with the impending changes coming in June everyone else will too in Null Sec) so if I want to use the stockpile feature to track the levels of each mineral that I have for various purposes, I cant so long as it is in an "Unknown Location".

**Comment by colcrunch** [comment]
Never mind, I forgot to update the structures... though there are still some "Unknown Locations"

**Comment by GoldenGnu** [comment]
ATM. There are 2 sources of unknown location I know about:
- Customs Offices ([ESI Feature Request](https://github.com/esi/esi-issues/issues/685))
- Destroyed PI structures ([ESI bug report](https://github.com/esi/esi-issues/issues/943))
   - A workaround will be implemented for this in the next jEveAssets release

If you find any other unknown locations, please, let me know...
