### ISSUE TITLE
When sell contracts expire they are no longer counted in the Tracker until they are deleted

### ISSUE THREAD

**Issue by jpkoester1** [GoldenGnu/jeveassets#473]
When a sell contract expires the items that are part of the contract are only put back into the hangar after the contract is deleted. Until that time the tracker shows an incorrect net worth. 2 possible fixes:

1. include sell contracts as contracts until they are deleted
2. somehow include the value of the assets that are part of the contract in the assets

![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/f9f27d5c-c04c-4e29-b52b-bcfd95f76380)

![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/e4f72c2f-c2ef-46fd-826e-882b0276ad34)

**Comment by jpkoester1** [comment]
I think option 1 would be more straight forward and more intuitive since the items are still bound in the contract at that time

**Comment by GoldenGnu** [comment]
Contracts are complicated - items can both be included (sold) and excluded (bought), and I think a mix of include and included (trade)? additionally your characters can be one or all of the issuer, issuer corp, assignee, acceptor.

This idea have come up multiple times, but, none ever created an issue.

ATM price is used as that is what on part of the contract estimate the contract to, which seems like a reasonable way to evaluate the value of the contract.

I want to add an option to use assets value instead, but, that will work really really bad for things that are not on the market as they will have a value of zero.

I want to add this, but, there isn’t any perfect solution that fit everything. And it will be complicated to add.


Just wanted to share why this wasn’t done already. Thank you for your feature suggestion

**Comment by jpkoester1** [comment]
Why can't you just treat expired contracts in the same way you treat active contracts (with regards to the tracker). Right now expired contracts and their content are completely disregarded in the tracker. Example

Day 0: I have a fitted Marauder that is worth 3 billion ISK sitting in my hangar

Tracker shows:
Contracts: 0 ISK
Assets : 3 billion ISK

Day 1: I decide to put up a sell contract with that Marauder with "I will receive 2.8 billion ISK"

Tracker shows:
Contracts: 2.8 billion ISK
Assets: 0 ISK

Day 91: The contract expires without anyone having bought the Marauder

right now Tracker shows:
Contracts: 0 ISK
Assets: 0 ISK

my proposal would be to continue keeping the value on the Contracts until it is deleted
Contracts: 2.8 billion ISK
Assets 0 ISK

Day 92: I delete the expired contract. Assets from that contract are once again in the hangar:

Tracker shows:
Contracts: 0 ISK
Assets: 3 billion ISK (or whatever the current market value of that Marauder fit is)

**Comment by jpkoester1** [comment]
Also, thanks for being so responsive, but make sure to enjoy your vacation. This is not an urgent request.

**Comment by jpkoester1** [comment]
Also rereading your answer, I think there is somewhat of a misunderstanding here. I am not asking for the valuation logic for contracts to change. I believe that the current logic based on the ISK values in the price and rewards column seems like a good proxy for the net value of the exchanged items on item exchange contracts. 

What I am asking for in this issue is that expired, but not deleted contracts are not completely disregarded in the tracker but instead still included as if they were still active (since the items are still bound inside and not visible in the assets).

**Comment by GoldenGnu** [comment]
Looks like I didn’t actually read the issue. Yes, this will be fixed for the next release. It’s just wrong logic, which should be easy to fix (hopefully)

**Comment by GoldenGnu** [comment]
Released in 7.9.1
