### ISSUE TITLE
When including corporation contracts in the asset view the owner should be the corp instead of the character

### ISSUE THREAD

**Issue by jpkoester1** [GoldenGnu/jeveassets#476]
I have set the "Include sell contracts" flag for the Assets tool:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/a0f60f16-d725-47e3-9808-78df9b6fa9b7)

In the Assets tool I can see a contract that has one of my characters set as its owner:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/6d7ddff5-ab75-4c55-b2ce-0d86e81830cc)

In the contract tool however, I can see that that contract is not owned by that character, but instead is owned by the Corporation:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/dfcb3c8c-a49a-4dd5-9cb0-ddc4a4a3ae11)

(same behaviour in the Tree view as well)

When including contracts in the asset windows (assets and tree) the owner should be set by the following logic:

If contract.Corporation == Yes then contract.IssuerCorp else contract.Issuer

looks like you tried something like that in the past, not sure why that would be commented out:
![image](https://github.com/GoldenGnu/jeveassets/assets/66028066/1d911ef2-45f2-409e-ae90-3e84c432ad30)

Do you remember what issues you ran into here?

Thanks and best regards!

**Comment by GoldenGnu** [comment]
In jEveAssets the owner is the character/corporation that got the data, if you want the corporation to be the owner, you need to add a corporation account for the corporation in question. Luckily the corporation contracts endpoint doesn’t require any roles in the corporation and is available to all members.

However, if you actually have a corporation account for the corporation, then I will consider this a bug, as it should use the corporation contracts, for corporations.

Please, let me know if this resolves your issue or if it is a bug.

**Comment by GoldenGnu** [comment]
Released in 7.9.1
