### ISSUE TITLE
Stuck industry jobs

### ISSUE THREAD

**Issue by sdennie** [GoldenGnu/jeveassets#480]
I recently came back after a year break and all the industry jobs I had running when I came back are now stuck and accounting towards Stockpiles and double counting the blueprints in Assets.  All of these jobs were listed as "Archived" in the Industry Jobs tab with a blank "Completed By" column.  I manually set all these jobs to "Canceled" but they are still counting towards Stockpile Manufacturing tallies.  I have also tried setting them to "Delivered" but the Stockpile tallies (and double counting in Assets) persists.

Is there any way to remove these stuck jobs without resetting years of history?  This is using version 7.9.0.

**Comment by sdennie** [comment]
To update this, unchecking Options->Save Industry Jobs History and updating cleared all these jobs.  This is still a bug of some flavor but, the workaround is simple enough.

**Comment by GoldenGnu** [comment]
Released in 7.9.1
