### ISSUE TITLE
Stockpile and industry (BPO copy): Industry column not showing industry copying jobs

### ISSUE THREAD

**Issue by Nolivfr** [GoldenGnu/jeveassets#482]
Hi,

In Stockpile, the industry column for BPCs does not show the number of copies from industry jobs (BPO copying) but shows instead the number of manufactured item from the BPC (as well in the stock, total stock, surplus etc.)
Stockpile BPCs also track items produced by BPCs instead of the item "blueprint copy".

![image](https://github.com/user-attachments/assets/ac2cadb2-0378-4496-af25-7364991684a7)

![image](https://github.com/user-attachments/assets/b8fee5ec-6e4a-4568-b2c7-fb47bf00aa18)

Is it possible to display the number of copies of BPCs being produced from industry jobs instead of the manufacturing jobs? The manufacturing job already is already displayed for the stockpiled item.

**Comment by GoldenGnu** [comment]
Released in 7.9.1
