### ISSUE TITLE
Tracker Asset Location Filter - auto-select new locations.

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#488]
There is a checkbox to add new locations selected (default is ON).

Checking it off only works for the current session. After quit, restart - it is selected again.

FER: change the default to off.

**Comment by GoldenGnu** [comment]
The default is not going to be changed to off, as that would mean any new location would be filtered out, that is not what most people want, the want to see the entire picture, not only the assets they had the first time they used jEveAssets. However, if it’s checked off, it should stay off.

**Comment by GoldenGnu** [comment]
Released in 7.9.1
