### ISSUE TITLE
Stockpile - Fittings

### ISSUE THREAD

**Issue by ekisner** [GoldenGnu/jeveassets#49]
Would love to be able to add fittings to stockpiles.  To allow tracking of doctrine stock compliance.

For example, I'm required to maintain a set number of ships in certain systems.  In all cases, I never fit rigs until the ship's ready to undock (so that shipping them out to a new system doesn't require destruction of rigs).  The rigs, per the multi-fit tool, end up in the cargo though, so they're still contained in the fitted ship's cargo.

To build on this further, I don't need one of everything in the doctrine, I just need "this, this or this, this and this".  The ability to use logical and/or groupings in the stockpile target qty would facilitate this.

**Comment by GoldenGnu** [comment]
That functionality already exits?

There is a `Import` button on the stockpile toolbar that allow you to import EFT fittings.

**Comment by ekisner** [comment]
Oh... oh my.  That is beautiful.  I greatly appreciate your time, wasted as it was on my stupidity.
