### ISSUE TITLE
Graph/Tracker profile selection (sort)

### ISSUE THREAD

**Issue by aixtools** [GoldenGnu/jeveassets#491]
* atm I cannot discover what the 'sort' option is for profiles - so I'll name it `random history` ie, whatever order characters first appeared in jeveassets.
* at a minimum would like to see corporation and character profiles sorted separately, alphabetical, e.g.
* I'd choose for corps on top, but order is open to discussion

* Toggle if (de-) selecting a corp also (de-)selects all characters currently associated with that corp.
* for the deselect I am thinkin in particular for gett a list of characters who have mined a corporate moon, but are not in a known (ie, personally managed) corp

**Comment by GoldenGnu** [comment]
Same issue in the tracker.

Either sort by name or by name with corporations first.

**Comment by GoldenGnu** [comment]
This is just going to be sorting by name.
However, feel free to make new issues for the rest of features in this issue.

**Comment by GoldenGnu** [comment]
Released in 7.9.1
