### ISSUE TITLE
BUG: stockpiles collapsing after edit

### ISSUE THREAD

**Issue by EdThelleres** [GoldenGnu/jeveassets#497]
When adding items/BPs to a stockpile all stockpiles in the same group get collapsed. Seems to happen only when groups/stockpiles are collpased using the buttons.

Steps to reproduce:
1) Have at least two groups with some stockpiles
2) collapse groups and stockpiles using the buttons
3) unfold a stockpile
4) add item to the stockpile

Version: 7.9.1

**Comment by GoldenGnu** [comment]
Released in 7.9.2
