### ISSUE TITLE
Feature to check current market order's underbid status

### ISSUE THREAD

**Issue by mandutt** [GoldenGnu/jeveassets#51]
Formal 'Market orders' tab could be renamed to 'Market order history', and make a new tab named 'Market order status'.
'Market order status' tab should work separated with data update, but can have its own sync button only intended to sync with current ongoing market order and station's price.
(No influence on other asset data)
So user can check own market order's underbid status without syncing whole data.
I have about 60 ongoing market orders now and it would be good if I can check underbid status at one glance 😃

**Comment by deadlybulb** [comment]
Here's some data and notes to help GG (I've been pulling and archiving market data for quite a while):

* The market endpoint is per region, so you need to pull the whole region even if you only want a single type.  This is what made the aggregators so nice to use.
* It's now much easier to tell if an order is posted at a citadel, and where the citadel is located (for range computation purposes).  It's less fun to look up the name of the citadel (I believe jEveAssets already has a solution here).
* Pulling market data from a citadel is an authenticated endpoint.  If users need to see that data, then you'll need to add that scope to their ESI authentication.

At present, there are 105 regions but only a few of them have non-trivial markets.  Here's a breakdown (see if you can figure out which one is Jita :) ):

| region ID | sample order count | number of market endpoint pages |
|-|-|-|
| 10000001 | 18074 | 18 |
| 10000002 | 290226 | 290 |
| 10000003 | 1 | 0 |
| 10000004 | 0 | 0 |
| 10000005 | 133 | 0 |
| 10000006 | 9 | 0 |
| 10000007 | 0 | 0 |
| 10000008 | 35 | 0 |
| 10000009 | 129 | 0 |
| 10000010 | 14 | 0 |
| 10000011 | 2012 | 2 |
| 10000012 | 14741 | 14 |
| 10000013 | 64 | 0 |
| 10000014 | 380 | 0 |
| 10000015 | 4077 | 4 |
| 10000016 | 67632 | 67 |
| 10000017 | 36 | 0 |
| 10000018 | 2 | 0 |
| 10000019 | 0 | 0 |
| 10000020 | 38708 | 38 |
| 10000021 | 0 | 0 |
| 10000022 | 10866 | 10 |
| 10000023 | 4609 | 4 |
| 10000025 | 120 | 0 |
| 10000027 | 2 | 0 |
| 10000028 | 22941 | 22 |
| 10000029 | 2039 | 2 |
| 10000030 | 69410 | 69 |
| 10000031 | 212 | 0 |
| 10000032 | 106307 | 106 |
| 10000033 | 50811 | 50 |
| 10000034 | 11 | 0 |
| 10000035 | 832 | 0 |
| 10000036 | 14294 | 14 |
| 10000037 | 22414 | 22 |
| 10000038 | 10626 | 10 |
| 10000039 | 1698 | 1 |
| 10000040 | 4 | 0 |
| 10000041 | 13564 | 13 |
| 10000042 | 98222 | 98 |
| 10000043 | 150330 | 150 |
| 10000044 | 16452 | 16 |
| 10000045 | 0 | 0 |
| 10000046 | 8 | 0 |
| 10000047 | 803 | 0 |
| 10000048 | 36435 | 36 |
| 10000049 | 7421 | 7 |
| 10000050 | 156 | 0 |
| 10000051 | 58 | 0 |
| 10000052 | 24500 | 24 |
| 10000053 | 45 | 0 |
| 10000054 | 16468 | 16 |
| 10000055 | 78 | 0 |
| 10000056 | 40 | 0 |
| 10000057 | 3337 | 3 |
| 10000058 | 5245 | 5 |
| 10000059 | 503 | 0 |
| 10000060 | 5898 | 5 |
| 10000061 | 153 | 0 |
| 10000062 | 8 | 0 |
| 10000063 | 3 | 0 |
| 10000064 | 42522 | 42 |
| 10000065 | 20499 | 20 |
| 10000066 | 6 | 0 |
| 10000067 | 31173 | 31 |
| 10000068 | 27950 | 27 |
| 10000069 | 16444 | 16 |
| 11000001 | 0 | 0 |
| 11000002 | 0 | 0 |
| 11000003 | 0 | 0 |
| 11000004 | 0 | 0 |
| 11000005 | 0 | 0 |
| 11000006 | 0 | 0 |
| 11000007 | 0 | 0 |
| 11000008 | 0 | 0 |
| 11000009 | 0 | 0 |
| 11000010 | 0 | 0 |
| 11000011 | 0 | 0 |
| 11000012 | 0 | 0 |
| 11000013 | 0 | 0 |
| 11000014 | 0 | 0 |
| 11000015 | 0 | 0 |
| 11000016 | 0 | 0 |
| 11000017 | 0 | 0 |
| 11000018 | 0 | 0 |
| 11000019 | 0 | 0 |
| 11000020 | 0 | 0 |
| 11000021 | 0 | 0 |
| 11000022 | 0 | 0 |
| 11000023 | 0 | 0 |
| 11000024 | 0 | 0 |
| 11000025 | 0 | 0 |
| 11000026 | 0 | 0 |
| 11000027 | 0 | 0 |
| 11000028 | 0 | 0 |
| 11000029 | 0 | 0 |
| 11000030 | 0 | 0 |
| 11000031 | 1365 | 1 |
| 11000032 | 0 | 0 |
| 11000033 | 0 | 0 |
| 12000001 | 0 | 0 |
| 12000002 | 0 | 0 |
| 12000003 | 0 | 0 |
| 12000004 | 0 | 0 |
| 12000005 | 0 | 0 |

**Comment by GoldenGnu** [comment]
From user (Charlie Dimaggio):
> GoldenGnu, how difficult do you think it would be to pull down market data for the markets that an item order has been setup on? There's a lot of useful information in the market window and it would become invaluable if it was also possible to highlight orders that had been outbid. Further to that, I believe it is possible with ESI to then open the market window on a specific item. If you could have it so that when you double click on an item in the market list it saves a predefined number to the clipboard and then sends an ESI command to that character to get it to open the window in the characters eve client
That would be amazing for dealing with market orders

**Comment by GoldenGnu** [comment]
Released in 6.3.0
