### ISSUE TITLE
Suggestion: Add "Multibuy" style export for shopping list in Stockpiles

### ISSUE THREAD

**Issue by stasikos** [GoldenGnu/jeveassets#52]
Currently you have "Shopping List" export and copy feature, but it can't be really directly used in Eve "Multibuy" window cause it can't understand thousand's separator (like "20,000" is looking like "20" for it). 
It will be useful to have compatible export format so you can just copy-paste and buy entire restock list on market without editing shopping list by hand.

**Comment by GoldenGnu** [comment]
Thank you for you feature suggestion.
I couldn't agree more.
Feature accepted, but, no ETA, yet.

**Comment by GoldenGnu** [comment]
Released in 5.9.0
