### ISSUE TITLE
Sakht 0.1 system showing as 0.0 security

### ISSUE THREAD

**Issue by douglas24** [GoldenGnu/jeveassets#53]
Not sure if this is a systemic rounding problem or unique just to Sakht.

**Comment by deadlybulb** [comment]
Probably a rounding error.  In the SDE, security is listed as 0.0414994338176336.  So with "round up" that becomes 0.1

**Comment by GoldenGnu** [comment]
Looks like 0.1 is a special case (just like 0.0 is, as it will be negative to define the true security status). rounding up does not produce the correct result for anything above 0.1, those should all be rounded to nearest value.

This is the code I will be using in the future:
```Java
private String roundSecurity(double number) {
	if (number < 0) { //0.0
		number = 0;
	} else if (number > 0 && number < 0.1) { //0.1 (Add this to deal with 0.1 systems)
		number = 0.1;
	} else { //0.2 - 1.0
		number = number * 10;
		number = Math.round(number);
		number = number / 10;
	}
	return securityformater.format(number);
}
```
It affects a lot of 0.1 system, so, I will be releasing an updated data set with this corrected within a few days

@douglas24 Thank you very much for the bug report :)

**Comment by GoldenGnu** [comment]
From #esi https://eve-industry.org/export/CCP_ROUND.pdf
It's not exactly the same as my code, but, the output is the same.
Going to released the fixed data set very soon

**Comment by GoldenGnu** [comment]
Fix deployed
