### ISSUE TITLE
Request: Show Character Owner Column in Market Orders Made On Corporation Behalf

### ISSUE THREAD

**Issue by alexanderdarino** [GoldenGnu/jeveassets#54]
Presently, no option to display a column indicating which character placed the corporation order is available. This information is actually available in-game in the market window, so I would assume it is available via ESI.

**Comment by deadlybulb** [comment]
That info just became available as the "issued_by" field on market orders.  I just added it to EveKit last week.

**Comment by GoldenGnu** [comment]
This will be included in the next release, but, only for market orders where `issued_by` is available.

**Comment by GoldenGnu** [comment]
Released in 5.7.0
