### ISSUE TITLE
Option to export to clipboard for pasting into evepraisal

### ISSUE THREAD

**Issue by hedge00** [GoldenGnu/jeveassets#56]
The export feature would benefit from a quick way to export just the Name and Count columns of the current filter to clipboard for pasting into evepraisal and import into multibuy. Some cleanup should be done on the names of ship containers (eg. a ship container named 'TRAVEL (Claw)' would be named just 'Claw') so they can be recognized. Also duplicate entries should be merged.

A good way to implement this would be a separate button named Clipboard Export that copies straight to clipboard without opening a dialog.

**Comment by GoldenGnu** [comment]
See also #6

**Comment by AnrDaemon** [comment]
Did you forgot to close this duplicate?

**Comment by GoldenGnu** [comment]
This will be included in the next feature release.

The following will be added to the popup/table menu:

1.  `Lookup > Market > Evepraisal` will create a new persistent evepraisal for the selected items and open it in the browser. 
2.  `Copy+ > Eve MultiBuy` will open a dialog box allow you to copy the selected item in Eve MultiBuy format (this format is compatible with evepraisal)

> duplicate entries should be merged ✔️

**Comment by GoldenGnu** [comment]
Released in 5.9.0
