### ISSUE TITLE
Skill search?

### ISSUE THREAD

**Issue by douglas24** [GoldenGnu/jeveassets#59]
Is it possible to search skills of all characters added with the results showing the levels? I thought this was already in the program (maybe the old API version?) but couldn't find it.

**Comment by GoldenGnu** [comment]
Yes, skills was part of the assets list for a while, because of a ESI bug.
They're no longer returned by ESI via the assets endpoints, and therefor are no longer in jEveAssets either.
They're not going to return. As skills are outside the scope of jEveAssets.
