### ISSUE TITLE
Values in the tree tab:

### ISSUE THREAD

**Issue by charliedimaggio** [GoldenGnu/jeveassets#64]
The tree tab works well when you are using it to track the value in regions and Citadels/Stations, but it does not work so well once you get down to hangars, corporation hangars and ships. It would make more sense to have Industry Jobs grouped together, also hangars and then the offices, so it makes it much easier to track the values contained within those subgroups. If possible, instead of the value of the ship being displayed, it might be better to have the total value of the ship plus fit and cargo and then the breakdown of the values under a plus/minus control. This would allow us to quickly track down where valuable items are in busy and complex corporations with many hangars.

Thanks Golden Gnu. Always a pleasure using your program

**Comment by GoldenGnu** [comment]
So, the way this is going to implemented is that the price will stay unchanged and the value will include all sup-items. That way you will still be able to see the value of ships and containers

**Comment by charliedimaggio** [comment]
Hi GoldenGnu, you asked me to create a new issue, but I found this one when I tried to create it. I noted that I did not mention station containers, so just mentioning that here.

Thanks as always

**Comment by GoldenGnu** [comment]
Released in 6.1.0
