### ISSUE TITLE
Another suggestion

### ISSUE THREAD

**Issue by Darkchyylde** [GoldenGnu/jeveassets#67]
For the "Locations" Section, allow for skipping of the system selection (or add in an option for wormholes) for stuff people have in wormholes, so it's not stuck listed as [Unknown Location #xxxxxxxxxxxxxxxx]

**Comment by GoldenGnu** [comment]
I assume you're referring to to renaming the unknown locations?

All the wormhole system are available in the drop system selection dialog. If you don't know what the system name is, just select a random wormhole system.

Does that resolve your issue?

**Comment by crmason2** [comment]
@GoldenGnu Propose closing this issue since it's 4 years without a response.

**Comment by GoldenGnu** [comment]
Yes, that makes sense - thanks 👍
