### ISSUE TITLE
Update Data on Schedule

### ISSUE THREAD

**Issue by cbrothers** [GoldenGnu/jeveassets#69]
would it be possible to either allow the program to be run from the commandline with some flag so we can run it using task scheduler to update the char data, or have an option for the app update the data every X minutes automatically.

**Comment by GoldenGnu** [comment]
It would be possible and some actually said they would contribute it, but, the work was never finished.
It was worked in the https://github.com/miikkaheikkila/jeveassets fork.

A very good alternative already exist: [EveKit](https://evekit.orbital.enterprises/#/qs). It's a much better option in my opinion, as it will update as often as allowed and save all history. Then you can just update jEveAssets at your convenance.

Therefor, I'm not going to implement this feature myself, but, I will accept it as a contribution.

**Comment by cbrothers** [comment]
Thanks for the reply - I hadn't looked to deeply into EveKit, but it may warrant some investigation.

**Comment by GoldenGnu** [comment]
This is now completed and will be released in the next feature release (5.9.0 or later)

## It will work as follow

With splash screen progress
```java -jar jeveassets.jar" -backgroundupdate```

Without splash screen
``` java -Djava.awt.headless=true -jar jeveassets.jar" -backgroundupdate```

**Comment by GoldenGnu** [comment]
Released in 5.9.0
