### ISSUE TITLE
Color palette for dark desktops.

### ISSUE THREAD

**Issue by Khaemwese** [GoldenGnu/jeveassets#70]
It's very hard to see the highlighted cells when using a dark desktop theme. I'm using Linux Gtk Adwaita-dark and java GTKLookAndFeel, but I suppose this would be an issue for other platforms as well. Using the Strong Colors helps in some cases, but BPO's for example, are pretty much unreadable. The problem is that the highlight colors are very light and in dark desktops, the text is white. May I suggest an option for dark desktops? Or maybe darken the Strong colors option a bit? Thanks.

P.S. Thanks for keeping this project alive!!!

**Comment by GoldenGnu** [comment]
Most colors are now customizable (Released in 6.4.0).
Reference: #115 
I'm going to close this issue, if you still need changed to make your dark theme work, please, leave a comment explaining what you need and I will reopen this issue
