### ISSUE TITLE
Feature Request: Add "Total Volume/Value" Column to Stockpiles (and Elsewhere)

### ISSUE THREAD

**Issue by alexanderdarino** [GoldenGnu/jeveassets#71]
Stockpiles has Stock/Surplus Volume/Value columns, but not one for total (the sum of stock + surplus). Would be convenient to have a total column!

**Comment by GoldenGnu** [comment]
stock + surplus make no sense to me. It's: `[what you own] + [what you own] - [what you need]`
It just doesn't make sense what you would use this for...
I'm going to close this issue.
If someone can explain how this would be useful, please, make a comment and I will reopen the issue
