### ISSUE TITLE
Feature Request: Regular Expression Filtering

### ISSUE THREAD

**Issue by alexanderdarino** [GoldenGnu/jeveassets#72]
In addition to the existing filters such as "Contains" and "Less Than", it's be nice to have a "Starts/Ends With" Filter. Example use case: We can specify "Ends with S/M/L/XL" to filter ammo by size.

**Comment by deadlybulb** [comment]
At this point, I think we should just add a regular expression matcher which would subsume start/end and many other things.

**Comment by AnrDaemon** [comment]
+1 for RegExp search.

**Comment by GoldenGnu** [comment]
Released in 6.0.0
