### ISSUE TITLE
javaw running jeveassets hits 99-100% CPU when trying to launch, fails to actually launch

### ISSUE THREAD

**Issue by rossos** [GoldenGnu/jeveassets#74]
Running on Windows 7, 64-bit. The problem seems inconsistent, as some times I am able to open the app in a reasonable amount of time, other times I have let javaw sit there for 10-20 minutes and not seen the progress bar in the jEVEassets splash screen move at all, until finally giving up and killing the process.

Any thoughts on how to debug this? If I try a re-install, is there a manual way to ensure my data is preserved?

**Comment by deadlybulb** [comment]
If you're on windows, your data will be saved in a .jeveassets directory in user home.  Copy that somewhere safe and you should be able to reinstall.

There could be many reasons for the behavior you're seeing, but the first place to check would be the jeveassets.log.  You should be able to find that in .jeveassets/jeveassets.log.  That should hopefully tell you where it's getting stuck on startup.

If this only happens during startup, it sounds like it may be having trouble calling home to check for updates (e.g. a network problem).  That's my best guess at the moment.

**Comment by rossos** [comment]
Thanks! That was helpful in starting to track some things down.

From the jeveassets.log file, it looks like the program is hanging immediately after the line
`Loading profile: Default`

Looking back through the older logs for the last apparently successful launch, the next line should be something like
`C:\...\jeveassets\profiles\#Default.xml loaded`

This appears to be a 380MB (!) XML file that jeveassets is struggling mightily to parse. Is that filesize in a normal range?

I'm also starting to wonder if a recent Java update has borked something for me, as this all started happening fairly recently.

**Comment by rossos** [comment]
Finally had time to just let the thing run as long as it wanted, and after a good long while I finally got

`Critical Error`
`Java has run out of memory`
`To avoid this error you can use jmemory.jar (instead of jeveassets.jar)`

Oddly enough, using jmemory.jar still causes the Critical Error to appear, only *much* sooner.

**Comment by deadlybulb** [comment]
Glad to hear you got things working again.  Was the backup file about the same size as the original?  Would have been interesting to diff the two files.  That might have pointed to the location of the bug.  It sounds like the issue wasn't the file size, but some garbage in the file that caused jeveassets to get stuck.

**Comment by rossos** [comment]
The same behavior presented the next time I started jeveassets. Again, deleting the *#Default.XML* file and replacing it with *#Default.BAC* allowed me to launch: javaw still used up full CPU and 2.1-ish GB of memory, but only for a few moments before going on to load the application's GUI.

Since (paradoxically, to my mind) .jeveassets\profiles\#Default.xml contains my actual assets/market/blueprints/etc. data in XML format, I assume something in my assets/etc. list is what causes the application to hang. I haven't done a full diff, but this isn't likely to very useful, I think: every single changed assets count and market order update is going to show up in that kind of diff.

I guess I can just keep deleting my profile XML file before each launch, but that seems a bit silly.  :)

**Comment by deadlybulb** [comment]
Is the backup file the same size as the original?

**Comment by rossos** [comment]
They are very similar in size, but any new XML profile file that seems to "break" things is always slightly larger: 388-400MB instead of the backup's 385MB filesize.

**Comment by rossos** [comment]
The problem now persists even when using the previously "good" version of my profile XML file.

Delving a bit into the Windows7 Resource Monitor, javaw.exe is using up 92% of my CPU resources on average. There is also a "wait chain" active: *One of more threads of javaw are waiting to finish network I/O*

Is my CPU spinning because jeveassets is trying to do something asynchronously, but failing? With the mention of network I/O, could there be a race condition with retrieving ESI account information, or some other network data that would normally be fetched very early on, while the application was still loading with the splash screen?

**Comment by deadlybulb** [comment]
Are you using EveKit or ESI to refresh your data?

**Comment by deadlybulb** [comment]
Oh wait, this dies during start so that shouldn't matter.

**Comment by rossos** [comment]
I can't launch it any more to check (!), but I'm fairly certain I have everything set up to use ESI, fwiw.

**Comment by GoldenGnu** [comment]
Sorry for the very very late reply to this issue.
High CPU is usually a sign jEveAssets is running out of memory.
You can run jEveAssets with `jmemory.jar` to avoid the problem.
First time you run it, it will crash or take forever to start (don't worry, just force kill it if you have to).
once it have been run a single time the file `jmemory.properties` should have been created.
You can now open that file with notepad
change `xmx=1g` to `xmx=4g` save the file and run with `jmemory.jar` again.
If jEveAssets is still slow keep increasing the number: `xmx=5g`, `xmx=6g`, etc. until it just works.

**Comment by GoldenGnu** [comment]
Going to close this.
Please, leave comment if you want this re-open
