### ISSUE TITLE
JEVEASSETS fails to start. W10, using Java SEDK 11.0.1 64 bit.

### ISSUE THREAD

**Issue by bugme143** [GoldenGnu/jeveassets#75]
[hs_err_pid13248.log](https://github.com/GoldenGnu/jeveassets/files/2665823/hs_err_pid13248.log)

I'm using the SEDK 11.0.1 because it's required for another java applet that I use.

**Comment by deadlybulb** [comment]
Not sure when you'll get a response to this, GG has been out for a while.  I assume you can reproduce this easily?  If I get some time over the holiday I'll see if I can figure this out.  I've never tried jEveAssets under anything beyond JDK 8.

**Comment by Jonnyw2k** [comment]
You can download the JRE tar.gz from: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html and extract into its own folder and run `JREFolder\Bin\Javaw.exe -jar jeveassets.jar` without effecting your other installation of Java

**Comment by GoldenGnu** [comment]
I only tests jEveAssets with latest official Oracle Jave 8 release.
This will be case for a while, until I figure out a good way to get my users to update the new major versions of Java.
For now I will mark this as "won't fix", however, I will happily review any PR to fix this.
