### ISSUE TITLE
Price History

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#76]
Each time we update, the app collects our API data but also it looks up the price for stuff. What if the app could save the prices information it collects and then we are able to see how the price has changed during time. In eve we can only see one year back in time, the app saves the data just like it does with our transaction history (in EVE its 60 days or 1000 entries, but we can see more than that in the app) so we could then be able to see further back than 1 year.

**Comment by GoldenGnu** [comment]
zKillboard have a API for price history (per type):
https://github.com/zKillboard/zKillboard/wiki/API-(Prices)
That would be really useful here.

**Comment by GoldenGnu** [comment]
- [x] GUI
  - [x] Tool
  - [x] TableMenu
- [ ] Backend
  - [ ] zKillboard
    - [x] Update from zKillboard API
    - [ ] Save/Load data
      - Only update each type once a day
      - Save to SQLite database
  - [ ] jEveAssets prices over time
    - [ ] Save/Load data
      - How often should we save the data? Once a day?
      - Save to SQLite database

**Comment by GoldenGnu** [comment]
Released in 7.3.0
