### ISSUE TITLE
Corp data (some) not available

### ISSUE THREAD

**Issue by JohJohOneThousand** [GoldenGnu/jeveassets#79]
Hi devs

Should data from the following Corporation areas be syncing, or is that still in dev? I added the corp account via ESI in jeveassets. All toon accounts update just fine. I'm attempting to access with a corp CEO toon account. Have been search for an answer for an hour.

My jeveassets update feedback:
```
ESI > Assets > Ingenium Heavy Industries
Not enough access privileges.
(Fix: Add Assets to the API Key)

ESI > Division Names > Ingenium Heavy Industries
Not enough access privileges.
(Fix: Add Division Names to the API Key)

ESI > Blueprints > Ingenium Heavy Industries
Not enough access privileges.
(Fix: Add Blueprints to the API Key)
```
Thanks for the great tool :)

**Comment by GoldenGnu** [comment]
Yes, the error message is a bit cryptic, but, it's most likely because the character you selected to import the corporation does not have the director role in-game.

You need the in-game director role to get assets via ESI.

Let me know if this resolves your issue.

**Comment by JohJohOneThousand** [comment]
Thanks for the reply. Turns out I was being impatient: the toon selected had only just been granted CEO access. All is working now.

Thanks again :)

**Comment by GoldenGnu** [comment]
Super, issue closed.
