### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#80]
Receiving error 500 in Data when using Update...

**Comment by GoldenGnu** [comment]
Please, email me the log.
See [how to email a bug report](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#bugs)

**Comment by GoldenGnu** [comment]
I'm going to assume this was the following ESI bug: https://github.com/esi/esi-issues/issues/1095
That issue is now resolved, so, I'm going to close this issue, please, create a new issue if you encounter this again.
