### ISSUE TITLE
Price Data (EveMarketer.com) Errors

### ISSUE THREAD

**Issue by NanoPish** [GoldenGnu/jeveassets#81]
Hey when I update data, I get Price Data (EveMarketer.com) Errors / Failed to update price data.

When I check evemarket.com it seems the website is up.

I believe there is an issue, which leads to me having no net worth listed. Any idea on how to diagnostic the issue ?

The mode access keys on evekit seem good and are unlimited / never expires.

**Comment by NanoPish** [comment]
I believe my issue comes from evekit where I can't manage to get ESI scopes OK.

Here I get "Not recently processed, ESI token missing scopes?" : https://imgur.com/a/OnG524A

And on the evekit quickstart, at the esi api key step, I log in to eve sso, accept all scopes, but it doesn't allow me to go next, as if an error occured silently : https://imgur.com/a/RiD2jBd

**Comment by deadlybulb** [comment]
I commented on the other ticket you raised but it looks like you authenticated to EveKit as NanoPish?  I don't see that account at all.  I'm checking the logs now.  Note that once you create an account with ESI tokens, it will take Evekit 10-15 minutes before it syncs your first data (many users on the service).

**Comment by deadlybulb** [comment]
Also note that if you get to the point where it asks if you want to change scopes, you can click skip instead unless you made a mistake in scope selection.  In this case, however, it's looking like it didn't persist your account login for some reason.

**Comment by NanoPish** [comment]
Hey that was not me. I check evekit again and it looks okay (green). Maybe I did not wait enough, or maybe it was before I was doing it near cluster shutdown. Thanks for you quick answer.
