### ISSUE TITLE
Please fix "Oursalert region"

### ISSUE THREAD

**Issue by AnrDaemon** [GoldenGnu/jeveassets#83]
It's [Oursulaert](https://zkillboard.com/system/Oursulaert).

**Comment by GoldenGnu** [comment]
What?

**Comment by AnrDaemon** [comment]
![20190309-202307-Clipboard](https://user-images.githubusercontent.com/6532485/54074904-859bd780-42a9-11e9-97eb-8c32ad36b135.png)

**Comment by GoldenGnu** [comment]
Thank you for clarifying that for me and thank you for your bug report. It may actually be hardcoded. I will try to get it fixed for the next release.

**Comment by GoldenGnu** [comment]
Ohh, you did a PR to, thanks! 👍

**Comment by GoldenGnu** [comment]
@AnrDaemon 
I have added you to the projects credits.txt and AboutDialog as "AnrDaemon".
If you prefer another name or alias, let me know

**Comment by GoldenGnu** [comment]
Released in 5.9.0

**Comment by AnrDaemon** [comment]
I'm fine with that, though I don't think it's warranted.
Thank you for your efforts, EVE would have been a much harder place without it.

**Comment by GoldenGnu** [comment]
Thank you for the kind words
Contributes are really rare for jEveAssets, so, I do appreciate it a lot when it happens.
You fixed a bug = ofc. you should be included.
