### ISSUE TITLE
Filter by Item Properties

### ISSUE THREAD

**Issue by alexanderdarino** [GoldenGnu/jeveassets#89]
In Stockpiles (and other applicable areas), I'd like to be able to filter items by intrinsic properties such as module slot, module size, metalevel, etc. Presently I use the tags feature for this, and it's very tedious and error prone to tag the items with these properties.

I use this information to prioritize the manufacturing and acquisition of items in my stockpiles. For example, if I am importing meta modules from Jita to sell to my local market and am running out, I might want to prioritize M4 modules first, or I might want to prioritize M-sized first, then S-sized, then L-sized, etc.

**Comment by GoldenGnu** [comment]
The only property that is already available in jEveAssets is meta level. I'm going to add a meta level column for the next release. The other properties will have to wait.

**Comment by GoldenGnu** [comment]
So, look into this a bit more. And there is no easy way to get the size (S/M/L/XL) of item types. It’s possible to get the slot location, though. As for the “etc.” you will need to tell me exactly what other properties you want added and why. Each property will take time to added and will increase the overall size of the data download, so there needs to be a good reason to add it.

**Comment by alexanderdarino** [comment]
Off the top of my head, the metalevel, size, and slot location are the most important. I'd imagine size would be the most important for weapons/ammo and repair modules (keeping in mind that XL and Capital are not necessarily the same thing as in the case of shield boosters). Having this information native in jEVEAssets would make my life a lot simpler and error prone over using tags! Thank you!

**Comment by GoldenGnu** [comment]
> Meta Level 

Already released in 5.9.0
> Slot location

Will probably been in 6.0.0
> Size

I tried working out size, but, the info is not easy to extract from the SDE.
It's mostly a market group thing and a charge size thing, but, both would require a lot of spaghetti code to get working, so, I'm going to decline to add that.

**Comment by GoldenGnu** [comment]
Slot size and charge size released in 7.6.0
