### ISSUE TITLE
Request: Treat Sell Orders as Assets

### ISSUE THREAD

**Issue by Aeistmer** [GoldenGnu/jeveassets#93]
Sometimes sell orders are way too high and that increases the value of my Accounts, even though I might not be able to sell them at that price. When lowering the sell order it says that I lost money even though i actually did not ever have it. 
Is it possible to add the feature/option to treat all sell orders with the value assigned in the price Data Option until they are sold?

**Comment by GoldenGnu** [comment]
Released in 6.1.0

**Comment by Aeistmer** [comment]
Thank you :)
