### ISSUE TITLE
Contract Appraisal Feedback

### ISSUE THREAD

**Issue by Noert** [GoldenGnu/jeveassets#95]
First thing I noticed in 6.0.0 is very odd values that don't seem to be based on anything.
Upon further digging, I discovered that BPC price is sometimes wildly out of proportion, but I can't set the price for BPCs manually, it just doens't accept it and keeps telling me that *random most useless BPC for t1 projectile ammo* costs 7 billion.

I think this needs adressing, there should be a way to override the automatic contract-derived price, otherwise contract valuation is useless.

**Comment by rihanshazih** [comment]
Thanks for reporting the odd prices! The values come from an api that i've built and while we thought we had eliminated strange pricing, there are still some values that are off the charts. While we're working on a solution, could you tell us which BPCs at which ME/TE have odd values?

**Comment by Noert** [comment]
Sure thing. 
Here's what I noticed: 
Carbonized Lead L Blueprint (BPC) (ME\TE 0; 1.5k runs; value 7.5B)
Nuclear S Blueprint (BPC)  (ME\TE 0;  1.5k run; value 7.4B)
Gas Cloud Harvester I Blueprint (BPC) (ME 10 TE 0; 300 runs; value 4.5B)
Scourge Heavy Missile Blueprint (BPC) (ME 10 TE 0; 1.5k runs; value 700M)

**Comment by GoldenGnu** [comment]
Thank you for your bug report.

The contract price API is still very new. @bahrmichael will keep improving the prices until they're as close to perfect as possible. He already improved it yesterday evening, so, it should already be better now.

Not being able to set a price for BPCs is a bug and I will look into that ASAP.

You can disable using the contract prices for BPCs:
1) Go to Options > Options.. > Contract Appraisal
2) Uncheck: Use contract prices as default price for BPCs

**Comment by Noert** [comment]
Thanks, I actually found that option after writing the report :) 
Will wait for the fix, you're doing great job.

**Comment by rihanshazih** [comment]
@Noert would you try updating the contract prices again and let me know if there are still any odd values?

**Comment by Noert** [comment]
Good progress, after a second contract update there's only one item from my list still glitched, Gas Cloud Harvester I Blueprint (BPC).

**Comment by rihanshazih** [comment]
I believe Gas Cloud Harvester I Blueprint (BPC) is now at "just" 430mil for 300 runs and not 4.5B anymore, correct?

**Comment by Noert** [comment]
> 
> 
> I believe Gas Cloud Harvester I Blueprint (BPC) is now at "just" 430mil for 300 runs and not 4.5B anymore, correct?

Oh yes, I only looked at the first few numbers, sorry. 
Still, that's quite a difference from what it actually costs

**Comment by GoldenGnu** [comment]
Small update on this:
I have found and fixed the bug with not being able to set the price for BPCs.

Next step is working with @rihanshazih to make a system where you can report bad prices, so, he will have a better idea of what prices are off.

Once that is done, I will release a new version. That said my life is pretty busy atm. because I’m moving next month.

**Comment by bahrmichael** [comment]
You can now report bad prices and I'll incorporate them into the pricing. Futhermore I am working on some improved algorithms.

**Comment by sirenbrian** [comment]
Just wanted to add another weird value for you. My Machariel BPCs are valued at 6.5B each. In Jita you can buy them about 240M isk.

**Comment by GoldenGnu** [comment]
Since jEveAssets 6.0.1 you can just set the correct price, and it can be reported to the API:
1) Right click the item with the wrong price
2) In the popup menu select `Price` > `Edit`
3) In the dialog enter the correct price and press `OK`
4) If this is the first time you're editing a price after 6.0.1 have been release, you will be asked to send the price as feedback to the Contract Appraisal API, if you click `OK` prices will automatically every time you edit a price. You can always change the setting: `Options` > `Options...` > `Contract Appraisal` > `Send edited prices as feedback to help improve the API`

**Comment by rihanshazih** [comment]
I've been working on a better pricing model over the last weeks and yesterday finally pushed new pricing data to production. This should result in less inflated prices for BPOs/BPCs, consideration how fast a contract was accepted or if it expired and faster response times from the api. The full transition away from the old model will likely take a few weeks (figuring out what the new model is still missing and updating the new model to also include those combinations).

**Comment by rihanshazih** [comment]
For all of you who like diagrams, here's a little chart that shows how many price points moved in which direction. tl;dr: Steady, but shift towards lower prices.

<img width="589" alt="Screen Shot 2019-05-25 at 11 22 07" src="https://user-images.githubusercontent.com/39265539/58367423-5af01100-7edf-11e9-9827-0653c8413d59.png">

**Comment by GoldenGnu** [comment]
@rihanshazih will continue to improve the prices as needed, as long as people will keep sending feedback. 
But, I feel we're out of "bug" territory now. So, changing this to enchantment.

**Comment by GoldenGnu** [comment]
Contract Appraisal now how Its own GitHub project and will be taking feedback directly from all of you.
So, I'm closing this issue. If you encounter anything wrong with the API, please make an issue in the contract appraisal project: https://github.com/rihanshazih/contracts-appraisal
